- README.md
- app/chain/message.py
- app/core/config.py
- app/modules/wechat/wechat.py
原来逻辑，输入n下一页，  self._current_page += 1
_current_page 已经+1了，如果下一页没有数据的话
再输入数字会超出索引
> fix 翻页bug|微信代理服务器配置

- app/utils/tokens.py
> Fix typo in tokens.py

- app/plugins/autosignin/sites/hd4fans.py
fix 提示headers object has no attribute 'headers.items()'的错误
> fix hd4fans 入参错误

- app/db/models/transferhistory.py
- app/db/transferhistory_oper.py
- app/plugins/mediasyncdel/__init__.py
支持emby、jellyfin
jellyfin自测。
支持plex需要增加解析plex日志相关逻辑
> feat 媒体库同步删除插件

- app/chain/download.py
- app/plugins/torrentremover/__init__.py
str(303782953.0).isdigit()因为有小数点，返回false
> fix 开始下载消息种子大小

- app/modules/transmission/transmission.py
- app/plugins/torrentremover/__init__.py
> fix TR连接、删种插件state报错

- app/chain/__init__.py
- app/chain/download.py
- app/modules/emby/__init__.py
- app/modules/emby/emby.py
- app/modules/jellyfin/__init__.py
- app/modules/jellyfin/jellyfin.py
- app/modules/plex/__init__.py
> fix no_exits

- app/api/endpoints/webhook.py
- app/modules/emby/__init__.py
- app/modules/emby/emby.py
- app/plugins/mediasyncdel/__init__.py
- app/schemas/mediaserver.py
配置已更新：https://github.com/thsrite/emby_sync_del_nt
scripter 需要get请求传param参数
post请求传不了param参数
所以加了个get请求的webhook api
> fix emby scripterx插件参数解析

- app/api/endpoints/site.py
假设同步了20个站点，手动设置了优先级、代理仿真流控等
后续某几个站挂了，想删除掉
目前只能重置站点+cookiecloud插件屏蔽+mp再次同步
但是之前设置的优先级、代理仿真等就没了，
感觉单个站点删除还是必要的
> feat 支持站点单个删除

- app/core/meta/metabase.py
- app/plugins/dirmonitor/__init__.py
> fix 目录监控转移消息统一发送

- app/plugins/dirmonitor/__init__.py
这里判断是不是写反了
应该判断目标目录是不是下载目录的子目录
防止监控下载目录，转移到目标目录后再次被监控到
> fix 目录监控判断

- app/chain/transfer.py
- app/plugins/dirmonitor/__init__.py
> fix 目录监控消息通知剧集集数错误

- app/plugins/autosignin/__init__.py
> fix 站点签到插件支持仅模拟登陆

- .dockerignore
> feat: optimize image size

- app/chain/download.py
> fix: 修复消息中百分比多乘了 100 的问题

- app/chain/download.py
- app/chain/site.py
> fix 交互命令消息原路返回

- app/plugins/speedlimiter/__init__.py
修复限速时通知错误问题，简单自测了一下是没问题的。没怎么写过python。请大佬看下有无问题！
> fix：限速通知速率展示问题

- README.md
- app/chain/transfer.py
- app/core/config.py
- app/db/models/transferhistory.py
- app/db/transferhistory_oper.py
- app/plugins/dirmonitor/__init__.py
- app/plugins/libraryscraper/__init__.py
- app/plugins/messageforward/__init__.py
根据src查询转移记录判断是否已处理
防止本次入库后转移了，但是转移不对删除后无法再次转移，必须重启
> fix 目录监控已处理逻辑 && feat 新增已入库媒体是否跟随TMDB信息变化开关，关闭则延用媒体库名称

- app/plugins/messageforward/__init__.py
> fix 消息转发插件清理缓存按钮

- app/utils/system.py
> feat: 优化容器id获取

- app/plugins/iyuuautoseed/__init__.py
> fix 辅种插件增加不辅种路径

- .github/workflows/build.yml
docker/metadata-action@v5
docker/setup-qemu-action@v3
docker/setup-buildx-action@v3
docker/login-action@v3
docker/build-push-action@v5
> bump: action jobs version

- app/modules/plex/plex.py
plex.py - 刷新媒体库：2 - /share/CACHEDEV1_DATA/Vol1/media_volume/series
↓↓↓
plex.py - 刷新媒体库：2 - /share/CACHEDEV1_DATA/Vol1/media_volume/series/洛基 (2021)/Season 1
> plex更精准的媒体库刷新

- app/modules/douban/__init__.py
- app/modules/douban/apiv2.py
- app/plugins/personmeta/__init__.py
> fix:演职员刮削优化

- app/plugins/rsssubscribe/__init__.py
> fix: RSS订阅插件下载没有启用代理问题

- app/plugins/cloudflarespeedtest/__init__.py
Typo fixed `envirment` -> `environment`
> Update __init__.py(typos fixed)

- app/api/endpoints/download.py
> fix 通过页面download传参username

- app/plugins/doubanrank/__init__.py
> fix 豆瓣榜单重复订阅

- app/plugins/autoclean/__init__.py
- app/schemas/history.py
配置方式参照目录监控，加强了插件功能
测试配置：
honue:30
豆瓣订阅:-1#src
清理源文件&媒体库文件
清理源文件
> enhance 定期清理插件

- app/chain/__init__.py
- app/core/metainfo.py
- 名称中如包含 {[tmdbid=xxx;type=xxx;s=xxx;e=xxx]}则会优先使用
> feat: 名称识别支持tmdbid等标记

- app/modules/emby/emby.py
- app/modules/jellyfin/jellyfin.py
- app/plugins/mediasyncdel/__init__.py
emby删除媒体webhook方式触发同步删除插件
目前电影、单集电视剧、整部电视剧ok
电视剧单季删除的webhook缺少Tmdb字段，已在emby社区反馈
> fix library delete webhook

- README.md
- app/api/endpoints/system.py
- app/chain/system.py
- app/core/config.py
- app/core/meta/metavideo.py
- app/helper/plugin.py
- update
动漫电影 剧场版识别失败
tmdb信息
修改前
修改后
搜了下tmdb，不少电影会在后面加上`剧场版`
名称识别不加上`剧场版`，会被识别为电视剧
> fix 动漫电影 剧场版

- app/modules/emby/emby.py
> fix emby webhook bug

- app/api/endpoints/plugin.py
我昨天没细看，就pr了（私密马赛，我那个pr会导致市场online插件重复，这个改应该就没问题了
> fix 本地插件未安装，但不在市场显示的情况（v2）

- app/modules/emby/emby.py
- app/modules/jellyfin/jellyfin.py
> fix emby/jellyfin首页继续观看、最近添加兼容共享路径

- app/modules/qbittorrent/__init__.py
> 正在下载的任务状态更新

- app/core/security.py
https://github.com/Radarr/Radarr/blob/b144482d6833c9191ce773dbb7cf72776b4562af/src/Radarr.Api.V3/openapi.json#L13016-L13028
> fix: 支持 Radarr 的 X-Api-Key 请求头

- app/api/endpoints/subscribe.py
处理 https://github.com/jxxghp/MoviePilot/commit/61d71b32ff1f206a8b57d663ee4c8d17d66ea04c 对于 tmdb 同名返回的问题
> fix: tmdb 同名返回已订阅

- app/modules/indexer/spider.py
resolve #1051
**复现步骤**
搜索标题后搜索 imdbid，`search_area` 会全部变成 0
> fix: search_area 错误删除

- README.md
- app/chain/search.py
- app/core/context.py
- app/modules/filetransfer/__init__.py
- app/modules/themoviedb/tmdbapi.py
- app/schemas/context.py
尝试从 tmdb 获取英文标题，不成功回滚为 `original_title`
#725 
#813 
#990 
#1008
> feat: english title from tmdb

- entrypoint
- update
1. 修复Shellcheck指出的问题，增强脚本稳定性。
2. 对于更新部分：采取先更新主程序和前端，插件和资源包再更新的原则；主要解决如果插件或资源包没有下载成功，主程序就无法更新成功的问题，但是其实资源包和插件是不影响主程序更新的。
> feat: startup and update script optimization

- app/core/meta/words.py
> 自定义识别词#注释 认为为注释

- app/log.py
> fix 日志恢复成文件名方式/插件调用内置模块的日志将会显示在插件日志

- app/api/endpoints/plugin.py
- app/core/plugin.py
- app/scheduler.py
- app/schemas/dashboard.py
```
def get_service(self):
"""
注册插件公共服务
[{
"id": "服务ID",
"name": "服务名称",
"trigger": "触发器：cron/interval/date/CronTrigger.from_crontab()",
"func": self.xxx,
"kwargs": {} # 定时器参数
}]
"""
my_services = []
if self._onlyonce:
self._onlyonce = False
if self._config:
self._config.update({"onlyonce": self._onlyonce})
self.update_config(self._config)
my_services.append({
"id": "complemented_history_onlyonce",
"name": "补全下载历史标签与分类(单次)",
"trigger": "date",
"func": self._complemented_history,
"kwargs": {
"run_date": datetime.datetime.now(
tz=pytz.timezone(settings.TZ)) + datetime.timedelta(seconds=3)
}
})
if self.get_state() and self._interval == "计划任务" or self._interval == "固定间隔":
args = {}
trigger = None
if self._interval == "固定间隔":
trigger = "interval"
if self._interval_unit == "小时":
args["hours"] = …
```
> 插件直接采用程序的定时任务模块, 可显示在前端页面

- app/modules/transmission/__init__.py
- app/modules/transmission/transmission.py
> [bugfix] tranmission 下载器下载选中集数的功能失效

- app/modules/filetransfer/__init__.py
fix:
1. 修复软连接文件不存在时, 覆盖转移
2. 修复默认覆盖方式为软连接时, stat状态查询
> fix: softlink exists

- app/chain/subscribe.py
> fix: subscribe search site scope error

- app/chain/subscribe.py
- app/helper/torrent.py
> feat: add min_seeders in filter_rule

- app/modules/jellyfin/jellyfin.py
小部分剧集无[xxx-S01E01-thumb.jpg]图片，调用返回父item图片
> fix 继续观看部分剧集图片

- app/helper/cookiecloud.py
- app/utils/common.py
CookieCloud拉取cookie时不再发送密钥，改为本地解密，增强安全性
> CookieCloud改为本地解密，增强安全性

- app/modules/qbittorrent/qbittorrent.py
修复功能:
QB远程控制插件，限速修复关联 https://github.com/jxxghp/MoviePilot-Plugins/issues/104
验证：
代码在本地可被正常运行，并以验证各项功能均正常使用，请求合并主分支。
> fix: 限速开关BUG 104

- app/chain/site.py
- app/helper/cookiecloud.py
每次获取Cookie信息前同步一次配置, 使配置修改实时生效
> CookieCloud配置支持实时更新

- app/modules/transmission/transmission.py
> feat: 增加session方法，用于获取tr的会话、配置信息

- app/chain/__init__.py
- app/chain/transfer.py
- app/modules/douban/__init__.py
- app/modules/themoviedb/__init__.py
- app/modules/themoviedb/scraper.py
> fix: metainfo for manual transfer

- app/modules/plex/plex.py
> feat: plex继续观看过滤黑名单

- app/modules/plex/plex.py
> feat: plex媒体数量统计过滤黑名单

- app/modules/plex/plex.py
- requirements.txt
- feat: plex最近添加过滤黑名单
- 同步更新上游plexapi [#1395](https://github.com/pkkid/python-plexapi/pull/1395)，请求参数规范化
> feat: plex最近添加过滤黑名单

- app/modules/plex/plex.py
> fix: 某些剧集parentThumb为None时的问题

- app/core/plugin.py
1. 增加计时器延迟执行避免调试时重载直接命中断点导致修改间隔无限期延长
2. 修改间隔调整为2，避免部分场景下，插件初始化修改本地文件配置触发重载的问题，本地部分插件初始化较长时间者约为1s左右
3. 原打算增加仅Python文件，但本地配置文件修改触发重载，似乎也是合适的，因此暂时保留。
> fix 热加载增加双重防抖

- app/log.py
> fix 开启DEBUG时，LOG文件也记录DEBUG日志

- app/modules/plex/plex.py
> fix: plex最近添加类型为show的资源

- app/chain/transfer.py
- app/utils/system.py
- 优化原盘目录硬链接的判断逻辑
- 硬链接重命名时调整为shutil.move实现
> fix #2265 优化硬链接的判断逻辑

- app/api/endpoints/plugin.py
- app/core/plugin.py
- app/db/models/plugindata.py
- app/db/plugindata_oper.py
> 重置插件时删除插件数据

- app/modules/plex/plex.py
- Plex sdk fetchItems 需要传入maxresults，否则内部会循环分页请求Plex Server
- 媒体库图片调整为为TTL缓存并缓存数调整为100，从而支持大型媒体库用户
> fix dashboard Plex卡片加载速度

- app/modules/filetransfer/__init__.py
#2447
挺特殊的需求，感觉大多数人应该用不到。反正都写了，提个PR
> add 自定义重命名新增季年份season_year #2447

- app/chain/__init__.py
- app/modules/douban/__init__.py
- app/schemas/__init__.py
- app/schemas/exception.py
- app/utils/common.py
- 目前处理链包装后，调用方无法获取到真正的异常/错误，如果通过修改返回值实现，考虑历史负债改动较大，因此通过raise_exception实现，涉及底层调整，改动存在较大影响，请协助评估该调整是否合理
- 针对exception包没有找到相对合适的位置，目前添加至app.schemas.exception，请协助评估该包定义是否合理
> 处理链run_module支持raise_exception

- app/api/endpoints/plugin.py
- app/core/plugin.py
- `is_plugin_exists`调整为判断包是否存在，修复插件包不存在但存在残余文件时，启动时不会重新安装的问题
- 卸载插件时移除`self._plugins.pop(pid)`逻辑
- 避免插件卸载后可执行文件必须重启才能再次安装该本地插件的问题
- 避免插件卸载后PluginManager必须重启才能从获取该本地插件数据的问题
- 调整安装逻辑，安装本地插件时依旧进行安装统计，避免默认打包本地插件时相关插件安装后不会被统计的问题
> fix plugin install and reg

- app/core/config.py
- app/core/plugin.py
- app/helper/plugin.py
- app/schemas/plugin.py
- app/utils/crypto.py
- 增加 `GITHUB_TOKEN_FOR_REPO`，支持特定仓库拉取
- 增加插件 auth_level `99`，支持插件私钥认证
> feat: 插件安装方案补充

- app/modules/plex/plex.py
- app/utils/http.py
- 个别情况，比如机智的凡人小子episode就是Poster，因此这里把episode的优先级降低，默认还是取art
> fix #2526 Backdrop优先调整为取art

- Dockerfile
fix https://github.com/jxxghp/MoviePilot/issues/2247
> fix: display id conflict

- app/api/endpoints/plugin.py
> fix(Plugin): 重置插件时初始化调整为reload，以保留默认配置

- app/command.py
- 调整为深复制，避免个别插件修改event后，其他引用处出现数据异常
> refactor(event): 事件处理调整为深复制，避免多线程环境下数据异常

- update
`update`错误日志报告，`Github`变成`PIP`了·
> `update`错误日志报告

- update
> `PIP_LOG`变量错误，应该为`GITHUB_LOG`

- app/utils/timer.py
- 添加`random_even_scheduler`用于尽可能平均生成定时器
> feat(TimerUtils): add random_even_scheduler

- app/modules/douban/__init__.py
- app/schemas/exception.py
- app/utils/common.py
> feat(rate-limiter): add rate limiter

- app/api/endpoints/transfer.py
> feat:手动转移文件增加从历史记录获取相关信息

- update
fix https://github.com/jxxghp/MoviePilot/issues/2688
> feat(docker): retry if download fails

- app/log.py
- app/utils/system.py
- config/app.env
- 重构 `log`，添加 `LogSettings`，用于独立管理日志配置选项，不再依赖通用 `settings`，为后续在 `settings` 中进行配置项校验时提供日志记录支持
> refactor(log): add support for configurable log settings in .env

- app/api/endpoints/login.py
- app/core/config.py
- config/app.env
- 添加 `AUXILIARY_AUTH_ENABLE`  参数，用于开启/关闭 辅助认证
> feat(auth): add AUXILIARY_AUTH_ENABLE for user authentication

- app/chain/mediaserver.py
- 跳过未启用的媒体服务器及无同步库的媒体服务器
- 完善日志记录
> fix(sync): skip disabled mediaservers and empty libraries

- app/modules/slack/__init__.py
- app/modules/synologychat/__init__.py
- app/schemas/system.py
> fix(push): correct client type

- app/core/config.py
- app/helper/plugin.py
- app/utils/system.py
- 插件安装策略整体重构，支持自动降级策略以及完善日志记录，同 #2626
- `SystemUtils` 增加 `execute_with_subprocess` 用于执行指令，降低命令注入风险
- `AUXILIARY_AUTH_ENABLE` 默认修改为False
> feat(plugin): implement fallback mechanism for install plugin

- app/api/endpoints/login.py
- database/versions/294b007932ef_2_0_0.py
- 兼容获取不到用户的场景
- 初始化用户时，头像默认调整为空
> fix(auth): handle scenario where the user is null

- app/modules/emby/emby.py
- app/modules/jellyfin/jellyfin.py
> refactor: 修改emby、jellyfin API url请求传参方式

- app/core/config.py
- app/core/plugin.py
- app/helper/plugin.py
- 优化插件安装逻辑，支持兼容性版本升级
- 优化在线插件获取，优先加载高版本的 `package.json`
- 将 `VERSION_FLAG` 设置为只读属性，防止外部修改（如环境变量）
> feat(plugin): improve plugin version upgrade and compatibility

- app/chain/mediaserver.py
- app/modules/emby/__init__.py
- app/modules/emby/emby.py
- app/modules/jellyfin/__init__.py
- app/modules/jellyfin/jellyfin.py
- app/modules/plex/__init__.py
- app/modules/plex/plex.py
- app/schemas/mediaserver.py
- MediaServerItem新增用户播放状态
- chain.mediaserver.items()增加分页参数
- 重构**emby**、**jellyfin** `get_items()` 实现，新增分页参数、不再通过递归获取单个项目详情来填充字段
> mediaServer新增用户播放状态

- app/command.py
- app/core/event.py
- app/core/plugin.py
- app/main.py
- app/schemas/types.py
- 重构事件总线，拆分广播事件以及链式事件，
- 支持事件优先级，优化事件消费模型
- 链式事件处理器支持优先级，支持可视化排序
- `command.py` 相关事件消费实现，调整至 `event.py`
- 增加 `ChainEventType` 用于链式事件
> refactor(event): optimize broadcast and chain event

- app/api/endpoints/storage.py
- app/chain/storage.py
- app/modules/filemanager/__init__.py
- app/modules/filemanager/storages/u115.py
- app/schemas/file.py
> feat: transType API

- app/api/endpoints/message.py
- app/chain/__init__.py
- app/chain/mediaserver.py
- app/helper/downloader.py
- app/helper/mediaserver.py
- app/helper/notification.py
- app/helper/serviceconfig.py
- app/modules/__init__.py
- app/modules/emby/__init__.py
- app/modules/jellyfin/__init__.py
- app/modules/plex/__init__.py
- app/modules/qbittorrent/__init__.py
- app/modules/slack/__init__.py
- app/modules/synologychat/__init__.py
- app/modules/telegram/__init__.py
- app/modules/transmission/__init__.py
- app/modules/vocechat/__init__.py
- app/modules/webpush/__init__.py
- app/modules/wechat/__init__.py
- 使用泛型重构服务的抽象基类，增强静态类型分析，优化下载器、媒体服务器和通知渠道的模块设计，简化服务实例的初始化和管理流程
- 重构服务配置的获取逻辑，新增了 `ServiceConfigHelper` 类。原有的 `NotificationHelper`、`MediaServerHelper` 等类代码迁移至 `ServiceConfigHelper`，后续调整为用于管理相应类别的服务实例，以便插件等模块能够共享服务实例，从而简化调用逻辑
> refactor (module): improve the implementation of base classes

- app/modules/qbittorrent/qbittorrent.py
> feat(downloader): support first_last_piece

- app/modules/emby/emby.py
- app/modules/jellyfin/jellyfin.py
- app/modules/plex/plex.py
> fix(mediaserver): improve data isolation handling

- app/core/plugin.py
> feat(plugin): broadcast PluginReload event when plugin reload

- app/core/config.py
- 重构 `Settings` ，抽取 `ConfigModel` 基类用于定义所有配置项及其类型和默认值
- 添加 `generic_type_validator`，用于自动校正 app.env 文件中的系统配置，统一处理配置中的空格、错误值等问题
> feat(config): preprocess env variables using Pydantic validators

- app/modules/__init__.py
- app/modules/emby/__init__.py
- app/modules/jellyfin/__init__.py
- app/modules/plex/__init__.py
- app/modules/qbittorrent/__init__.py
- app/modules/slack/__init__.py
- app/modules/synologychat/__init__.py
- app/modules/telegram/__init__.py
- app/modules/transmission/__init__.py
- app/modules/vocechat/__init__.py
- app/modules/webpush/__init__.py
- app/modules/wechat/__init__.py
- 修复了 Plex Webhook 参数错误的问题
- 完善 `getters` ，避免子类直接访问父类的内部变量
> fix(module): use getters for _instances and _configs in subclasses

- app/core/security.py
- app/utils/web.py
- 使用 `Security` 替代 `Depends`，确保 `Swagger` 文档正确生成认证方案，提高调试和开发效率
- `wallpaper` 接口新增缓存策略，缓解潜在的攻击风险
> refactor(security): replace Depends with Security and define schemes

- app/api/endpoints/download.py
- app/api/endpoints/mediaserver.py
- app/api/endpoints/message.py
- app/api/endpoints/search.py
- app/api/endpoints/system.py
- app/api/endpoints/user.py
- app/core/security.py
- app/modules/slack/__init__.py
- app/modules/telegram/__init__.py
- app/modules/vocechat/__init__.py
- 部分业务接口，还原 Token 验证，缓解潜在的攻击风险
- 部分匿名接口，模糊化错误提示语，缓解潜在的攻击风险
- 消息服务接口，增加统一的 `API_Token` 验证，缓解潜在的攻击风险
- 部分系统接口，使用 `Depends` 替代 Token 验证，保持认证一致性
- 部分媒体接口，增加 Token 验证，缓解潜在的攻击风险，并兼容了 v2 版本
> feat(security): enhance token validation and error handling across various interfaces

- app/utils/string.py
将重复的特殊字符 `—`[U+2014](https://symbl.cc/cn/2014/) 修改为 `―`[U+2015](https://symbl.cc/cn/2015/)
> fix: 修正重复的特殊字符

- app/chain/subscribe.py
- app/modules/filemanager/__init__.py
- 递归列出目录中所有文件, 修复获取不到`Seasion X`目录下`媒体文件`的bug
- 修正哈希值字段名
- 可能存在的问题: 依赖`网络`获取信息,请求失败则无法加载
> fix: 修复`我的订阅`中`文件`无法加载的问题

- app/api/endpoints/system.py
- app/utils/crypto.py
- app/utils/http.py
- 重构图片代理逻辑，将其整合到统一的 fetch_image 函数
- 添加了对 HTTP 缓存的支持，以提升性能并减少服务器负载
> feat(cache): add HTTP cache support for image proxy

- app/utils/security.py
- 修复了可信域名验证中的若干问题，提高 URL 解析和匹配的准确性
> fix(security): optimize URL validation

- app/modules/emby/__init__.py
> fix(mediaserver): update get_type return type to ModuleType for consistency

- app/chain/site.py
- app/schemas/types.py
- 支持站点数据刷新事件，事件类型命名为 `EventType.SiteRefreshed`，命名是否合适请评估
> feat(event): add SiteRefreshed event

- app/api/endpoints/user.py
- app/db/models/user.py
- app/schemas/user.py
- 增加通过 `id` 进行筛选并删除指定用户的API接口。
- 修复 `update_user` 使用错误的类型；原先用 `UserCreate` ,已调整为 `UserUpdate`
> feat(user): Add username modification function API.

- app/api/endpoints/login.py
- app/chain/user.py
- app/core/config.py
- app/core/event.py
- app/modules/emby/__init__.py
- app/modules/jellyfin/__init__.py
- app/schemas/event.py
- app/schemas/types.py
- 链式事件新增支持 `AuthVerification` 和 `AuthPassedIntercept` 
- `AuthVerification`：用于处理认证验证事件
- `AuthPassedIntercept`：用于处理认证通过后的拦截事件，如拦截媒体服务器渠道（如 Emby、Jellyfin）
- 添加了 `ChainEventData` 相关数据结构，从而更好的传递链接事件以及后续使用
> feat(chain): add auth event to ChainEventType

- app/api/endpoints/login.py
- app/schemas/token.py
> fix(login): 增加返回user_id

- app/chain/user.py
- 修复非 `password` 认证类型在禁用状态下仍然可以通过认证的问题
> fix(auth): prevent disabled users from authenticating

- app/api/endpoints/system.py
- app/startup/modules_initializer.py
- app/utils/system.py
- `clear` 调整为支持递归子目录
- 支持清理7天前的图片缓存文件
> fix(cache): support clear image cache

- app/core/config.py
- app/db/__init__.py
- config/app.env
- 调整了 `QueuePool` 的默认连接池参数，从而进一步降低高并发下的连接池超时导致无法正常响应的问题
- 引入对 `NullPool` 的支持，允许在配置中选择使用 `NullPool`，从而在高并发情况下避免连接池的资源争用
> feat(db): add pool class configuration and adjust connection settings

- app/core/config.py
- config/app.env
> fix(config): improve env update logic

- app/api/endpoints/plugin.py
- app/core/plugin.py
- app/scheduler.py
- 统一增加了插件状态检查，只有显式启用状态的插件才会返回对应的 API、Command 和服务
- API 与服务已支持热更新，Command 的热更新待进一步实现
> feat(plugin): add state check for commands, APIs, and services

- app/api/endpoints/plugin.py
- app/chain/command.py
- app/core/event.py
- app/schemas/types.py
- app/startup/plugins_initializer.py
- 重构远程命令实现，支持模块重载及插件启停等场景下的热更新
- 提供远程命令注册事件，支持插件针对远程命令进行前置过滤调整
> feat(command): optimize command registration event handling

- app/core/plugin.py
- app/helper/plugin.py
- app/startup/plugins_initializer.py
> feat(setup): complete missing dependencies installation

- app/modules/__init__.py
> fix(downloader): ensure default downloader config fallback

- app/core/plugin.py
- app/helper/plugin.py
- app/startup/plugins_initializer.py
> fix(setup): optimize logging

- app/chain/command.py
- app/schemas/event.py
> feat(commands): support background initialization

- app/modules/filter/__init__.py
filter - 种子 观众 - The Boy and the Heron 2023 1080p AMZN WEB-DL DDP5.1 H.264-ADWeb 不包含 ADE
> fix 种子过滤包含规则

- app/modules/telegram/telegram.py
- app/modules/wechat/wechat.py
- 优化企业微信消息请求逻辑，支持在Token过期时自动刷新并重新发送消息，同时在网络请求异常时增加自动重试机制
- 改进企业微信的分段请求逻辑，避免由于意外的长文本导致请求异常
- 修复了企业微信获取 Token 失败时，健康测试依旧通过的问题
- 增加了企业微信删除菜单的请求方法
- 修复了Telegram图片请求的缓存目录不存在时的异常问题
> refactor(wechat): optimize message handling and add menu deletion

- entrypoint
fix https://github.com/jxxghp/MoviePilot/issues/2892
> fix(docker): nginx directory permission issue

- app/modules/filter/__init__.py
DEBUG:   filter - 种子 观众 - The Boy and the Heron 2023 2160p USA UHD BluRay HEVC DV TrueHD 7.1 Atmos-Nest@Audies 不包含任何项 []
> fix dc3240e9

- app/chain/command.py
- app/modules/telegram/__init__.py
- app/modules/telegram/telegram.py
- app/modules/wechat/__init__.py
- app/modules/wechat/wechat.py
- app/utils/structures.py
- 支持`TG`、`企业微信`模块触发 CommandRegister 事件，用于在不同客户端上，注册不同的命令菜单
- 对企业微信的消息推送，进行了异常容错处理，避免遍历客户端时，部分客户端发生异常，导致后续所有客户端均无法正常推送
> feat(commands): support sending CommandRegister events for clients

- app/chain/transfer.py
- app/modules/filemanager/__init__.py
fix: #2926
- 修复无法整理原盘的问题
- 添加类型注解
> - 修复 整理`原盘`报错的问题

- app/helper/directory.py
> fix: #2974 #2963

- app/modules/filemanager/storages/local.py
https://github.com/jxxghp/MoviePilot/issues/2964  这个问题比较简单，不过我没有仔细看其他逻辑
> fix softlink

- app/scheduler.py
- 优化公共服务注册及移除逻辑，支持插件注册同名任务的多个实例，如签到插件注册同名的不定时2个任务
> fix(scheduler): optimize job registration and removal logic

- update
> 修复update脚本，版本号比较问题

- app/api/endpoints/storage.py
> fix: 修复`手动重命名`失败的问题

- app/chain/media.py
> 修复整理多季时`season.nfo`刮削错误的问题

- app/modules/filemanager/storages/alist.py
- app/schemas/system.py
- app/schemas/types.py
- app/utils/string.py
> feat: 增加 filemanager storages 类型：Alist

- app/api/endpoints/system.py
> feat(cache): add proxy support for specific domains in image caching

- app/chain/download.py
- app/chain/torrents.py
- app/core/context.py
- app/db/models/site.py
- app/modules/indexer/__init__.py
- app/schemas/context.py
- app/schemas/site.py
> feat: 站点管理增加`下载器`选择

- entrypoint
- nginx.conf
fix https://github.com/jxxghp/MoviePilot/issues/2951 fix https://github.com/jxxghp/MoviePilot/issues/2720
> feat(docker): nginx `client_max_body_size` configuration

- app/modules/qbittorrent/qbittorrent.py
- requirements.in
- https://github.com/rmartin16/qbittorrent-api/issues/500
- https://github.com/rmartin16/qbittorrent-api/releases/tag/v2024.11.69
> chore(qbittorrent): update qbittorrent-api to version 2024.11.69

- app/modules/filemanager/__init__.py
> fix: 某些情况下误删媒体文件的问题

- app/core/event.py
- app/modules/filemanager/__init__.py
- app/schemas/event.py
- app/schemas/types.py
> feat(event): support smart rename event

- app/modules/filemanager/__init__.py
- app/modules/themoviedb/tmdbapi.py
修复重命名时S0年份为None的问题
增加重命名配置剧集日期
> 修复重命名时S0年份为None的问题;增加重命名配置剧集日期

- app/chain/media.py
- app/core/config.py
- app/modules/themoviedb/scraper.py
修复S0刮削问题
修复某些情况下剧集根目录判断错误的问题
重命名格式支持S0重命名为Specials,SPs
> 修复S0刮削问题，修复某些情况下剧集根目录判断错误的问题，重命名时支持S0别名

- app/chain/__init__.py
- app/chain/transfer.py
- app/modules/filemanager/__init__.py
> refactor: change library type and category folder parameters to optional

- app/modules/indexer/spider/yema.py
* 使用新的搜索api，可不传categoryId
* 优化类目匹配逻辑，多个类目对应MP的一个TV类目
* 增加标签展示
* 使用上架时间作为发布时间
> feat(yemapt): update search api and enrich torrent content

- app/modules/indexer/spider/yema.py
> fix(yemapt): Check if the tag list is empty

- app/core/plugin.py
- app/scheduler.py
- 调整 `scheduler` 显式支持插件替换系统服务 
- 调整 `scheduler` 部分方法支持外部如插件调用
- 支持通过 `func_kwargs` 用于 `scheduler` 传递方法参数
> feat(scheduler): support plugin replacement for system services

- app/core/event.py
- app/modules/filemanager/__init__.py
- app/schemas/event.py
- app/schemas/types.py
- 将 `SmartRename` 调整为 `TransferRename`，以便后续添加更多整理类型事件
- 修正 `visualize_handlers` 方法，以适配订阅器的最新数据结构
> refactor(event): rename SmartRename to TransferRename

- app/api/endpoints/transfer.py
jxxghp/MoviePilot-Frontend#255
> 改进手动整理逻辑 关联后端 jxxghp/MoviePilot-Frontend#255

- app/api/endpoints/system.py
> fix(api): 修复规则测试未获取到媒体信息导致的过滤失败问题

- app/chain/subscribe.py
- 修复未定义订阅优先级规则时默认回退到搜索优先级规则的问题，默认将不再自动回退
> fix(subscribe): prevent fallback to search rules if not defined

- app/chain/subscribe.py
- 新增订阅搜索，N->R 调整至 `finally` 中执行，避免在某些情况下订阅刷新重复下载
> fix(subscribe): move state update to finally to prevent duplicates

- app/modules/emby/__init__.py
- app/modules/jellyfin/__init__.py
- app/modules/plex/__init__.py
- 修复了辅助认证失效的问题
- 允许指定媒体库服务进行辅助认证
> feat(auth): support specifying service for authentication

- app/api/endpoints/media.py
- Change incorrect reference from media_info to mediainfo
> fix(api): correct variable reference in media scraping logic

- app/chain/subscribe.py
- app/db/subscribe_oper.py
- `SubscribeChain` 调整为单例实现，针对 `match` 与 `search` 添加 `RLock`，避免订阅重复下载
- 部分逻辑容错处理
> fix(subscribe): add RLock to prevent duplicate subscription downloads

- app/chain/download.py
- app/schemas/event.py
- app/schemas/types.py
> feat(event): add ResourceSelection event for update resource contexts

- app/plugins/__init__.py
> feat(plugin): add username support for post_message

- app/chain/download.py
- app/chain/subscribe.py
- app/schemas/event.py
-  下载事件增加 `source` 的全链路跟踪
- 下载历史表 `note` 增加 `source` 记录
- 订阅下载，`source` 增加订阅信息传入
> feat(event): add source tracking in download event

- app/core/context.py
- app/modules/filter/__init__.py
- 在 `TorrentInfo` 类中添加 `pub_minutes` 方法以计算自发布以来的`分钟`数
- 在 FilterModule 中实现发布时间过滤
- 支持发布时间的单值和范围比较
> feat(filter): add publish time filter for torrents

- app/core/event.py
> feat(event): add support for priority in event registration

- app/core/event.py
- 注册事件时，已支持自动提取所有事件成员进行注册，移除不必要的代码
``` python
elif isinstance(event, type) and issubclass(event, (EventType, ChainEventType)):
for et in event.__members__.values():
self.add_event_listener(et, f, priority)
```
> fix(event): remove unnecessary code

- app/helper/torrent.py
> fix(download): optimize performance by checking binary content

- app/api/endpoints/subscribe.py
- app/schemas/types.py
> feat(event): add SubscribeDeleted event

- requirements.in
> fix(dependencies): pin python-115 version

- app/chain/subscribe.py
> fix(subscribe): avoid reinitializing the dictionary

- app/chain/subscribe.py
> feat(subscribe): optimize best version to support multiple states

- app/chain/download.py
- Simplify download path determination logic
- Remove redundant code for save path calculation
> refactor(app): optimize download path logic

- app/helper/plugin.py
- app/helper/subscribe.py
> fix(proxy): add proxy for MP_SERVER_HOST

- app/chain/recommend.py
> 当启用全局图片时，refresh_recommend 将支持后台预下载推荐图片资源，进一步提升加载效率( https://github.com/jxxghp/MoviePilot/pull/3590)
> feat(recommend): support caching poster images

- app/chain/recommend.py
- app/scheduler.py
- 支持分页缓存推荐数据，默认缓存 `5` 页，并允许外部进行调整
- 推荐缓存时长调整为 `24` 小时，刷新周期调整为 `24` 小时
> feat(recommend): support caching by page

- app/api/endpoints/history.py
- app/core/config.py
- requirements.in
- 引入 `jieba~=0.42.1` 用于分词搜索
- 新增 `TOKENIZED_SEARCH` 配置项，实现历史记录分词搜索，进一步提高搜索精度
> feat(config): add TOKENIZED_SEARCH

- app/monitor.py
- Rename 'size' parameter to 'file_size' in on_created and on_moved methods
- This change enhances code clarity and maintains consistency with other parts of the codebase
> refactor(app): improve code readability and consistency in FileMonitorHandler

- app/chain/transfer.py
> fix(transfer): handle task removal on media info failure

- app/chain/site.py
> feat(site): add proxy support for site sync

- app/log.py
- `Logger` 调整为更新引用，避免外部引用导致表现不一致的问题
- 大幅提升了日志堆栈处理的性能表现
>print("Original __analyze_stack_deep:", timeit.timeit(logger.origin_get_caller, number=1000))
print("Optimized __analyze_stack_deep:", timeit.timeit(logger.get_caller, number=1000)) 
>Original __analyze_stack_deep: 9.127494299998943
Optimized __analyze_stack_deep: 0.016246900002443
> perf(log): optimize get_caller for improved performance

- app/chain/site.py
修复馒头报错`本地時間誤差過大，請校準系統時間`导致的测试连通性失败
> 修复馒头连通性测试失败

- app/chain/site.py
> fix(site): handle NoneType for userdata.user_level in regex search

- app/helper/format.py
> fix: 指定集数范围

- app/core/cache.py
- app/modules/themoviedb/tmdbv3api/objs/trending.py
- app/scheduler.py
- 优化缓存 `region` 的管理策略，避免无意义的缓存策略
- 为缓存装饰器增加 `cache_clear` 方法，支持外部主动清理缓存
- 调整 TMDB `trending` 缓存的 `maxsize` 配置，从 1 增加至 1024，避免无意义的缓存策略
- `Scheduler` 清理缓存仅保留 `SchedulerChain().clear_cache()`，避免重复调用
> feat(cache): enhance cache region and decorator

- app/chain/recommend.py
- app/core/cache.py
- 增加 `CacheToolsBackend` 的缓存方案说明，移除 `recommend` 中每个方法的 `maxsize`
> feat(cache): remove maxsize from recommend_cache

- app/core/cache.py
- app/core/config.py
- app/scheduler.py
- app/startup/modules_initializer.py
**此 PR 新增了 `Redis` 作为缓存后端的支持，与现有的 `cachetools` 方案形成互补，为分布式和高性能场景提供了更灵活的缓存解决方案。主要功能和配置选项如下：**
1. **`CACHE_BACKEND_TYPE`**：  
- 描述：缓存类型，支持 `cachetools` 和 `redis`
- 默认值：`cachetools`
2. **`CACHE_BACKEND_URL`**：  
- 描述：外部缓存（如 Redis）的连接字符串，仅外部缓存需要配置
- 示例：`redis://:c7rpGZZRiTtqb43i4iCXDEkqh98jAaCnPtPi@192.168.50.99:36379`
3. **`CACHE_REDIS_MAXMEMORY`**：  
- 描述：Redis 缓存的最大内存限制，用于控制缓存总大小
- 默认值：  
- 未配置时，根据是否开启大内存模式动态设置：  
- **开启大内存模式**：`1024mb`
- **未开启大内存模式**：`256mb`
- 支持自定义值，例如：`512mb` 或 `2gb`
1. **动态 TTL 支持**：  
- 每个缓存项可单独设置过期时间（Time To Live, TTL）
- 提供灵活的过期策略，适配不同场景需求
2. **分区域（Region）管理**：  
- 通过命名空间隔离缓存区域，不同区域的键互不干扰
3. **内存限制与淘汰策略**：  
- 支持配置 Redis 的 `maxmemory` 和淘汰策略，例如 `allkeys-lru`、`volatile-lru` 等
- 当内存达到上限时，根据策略自动移除缓存项，确保性能稳定
1. **网络延迟**：  
- Redis 使用过程中可能因网络延迟导致缓存操作耗时增加，需视具体场景评估是否使用
2. …
> feat(redis): add Redis support

- app/core/cache.py
- app/modules/themoviedb/tmdbapi.py
1. `CacheBackend` 增加了 `exists` 方法，用于判断缓存键是否存在，提高缓存操作的灵活性
2. TMDB `match_web` 调整
- 增加限流器，防止高频请求导致的接口访问持续受限
- 支持通过代理访问 TMDB API，提升请求的稳定性
- 完善缓存策略，优化缓存命中率，减少重复请求
3. fix #3784
> fix(cache): enhance tmdb match_web rate-limiting and caching

- app/core/cache.py
> feat(cache): optimize serialization with type-based caching

- app/modules/fanart/__init__.py
- app/utils/limit.py
- 优化 `fanart` 图片请求的缓存策略  
- 完善限流器日志记录，避免错误记录
> fix(cache): enhance fanart image caching

- app/modules/filemanager/storages/alist.py
支持通过永久令牌的方式进行认证，以支持开启 2FA 的账户（相关 issue #3106）
> feat: 支持使用永久令牌进行认证

- app/core/context.py
- app/modules/themoviedb/scraper.py
- app/modules/themoviedb/tmdbapi.py
resolve #3822 
为nfo文件增加mpaa元素，用于支持按内容分级
> feat(TMDB): 增加内容分级的刮削

- app/modules/filemanager/__init__.py
- app/schemas/event.py
- app/schemas/types.py
- 新增 `TransferIntercept` 链式事件，用于整理文件前的逻辑处理，如拦截整理，删除潜在的洗版资源等
> feat(event): add TransferIntercept event for cancel transfer

- app/modules/wechat/wechat.py
> fix: 修复带路径的WECHAT_PROXY不生效

- app/modules/filter/__init__.py
> fix: 标签为"官组"的种子应识别为官种

- requirements.in
try to fix https://github.com/jxxghp/MoviePilot/issues/3731
> bump: docker version 6.1.3 to 7.1.0

- app/modules/jellyfin/__init__.py
- app/modules/plex/__init__.py
- app/modules/trimemedia/__init__.py
- app/modules/trimemedia/api.py
1. 除了emby，其余几个媒体服务器均发现了类似瑕疵。
2. 解决了飞牛搜索接口报错导致的媒体缺失问题
> 继续修复媒体缺失问题

- app/modules/trimemedia/__init__.py
- app/modules/trimemedia/api.py
- app/modules/trimemedia/trimemedia.py
> 提升飞牛服务端地址的兼容性

- app/core/meta/releasegroup.py
> perf: 放宽制作组后缀匹配

- app/db/downloadhistory_oper.py
- app/db/models/downloadhistory.py
- 使用`TransferHistory.list_by`相同逻辑
> refactor(db): optimize download history query logic

- app/helper/message.py
- database/versions/89d24811e894_2_1_4.py
- Fix syntax error in downloadAdded message template
> fix(database): improve message template

- app/modules/indexer/parser/yema.py
> update yemapt downloadsize

- app/utils/string.py
> _special_domains列表中添加pt.gtk.pw

- app/chain/transfer.py
- app/modules/transmission/transmission.py
- #4180 
- TR的get_torrent_tags()方法返回[]
> Fix tag issues

- app/modules/indexer/spider/mtorrent.py
> 修复馒头新版标签无法识别的问题

- app/helper/message.py
> fix 时间解析问题

- app/core/meta/metavideo.py
修改了`__init_video_encode`区别H26x和x26x的处理
添加了`HLG AV1 AVS DD+ DTS-HD HR Opus Vorbis`格式
> feat(meta): 扩展音视频格式匹配规则

- app/modules/filter/__init__.py
> fix: 优化 Blu-ray 匹配规则

- app/api/endpoints/media.py
- app/schemas/event.py
> fix: 确保名称识别正确兜底

- app/chain/search.py
- 使用 with 语句管理 ThreadPoolExecutor，确保线程池正确关闭
> fix(SearchChain): with 关闭线程池
