jxxghp/MoviePilot

README.md
app/core/config.py

如果 PROXY_HOST 填写 192.168.31.2:1081 的话
按照以前逻辑就是
return {
"http": "http://192.168.31.2:1081",
"https": "https://192.168.31.2:1081"
}
实际上 https://192.168.31.2:1081 访问不通，导致tg、tmdb都不法代理访问
不如让用户直接填写http(s)://ip:port

fix PROXY_HOST变量设置后，仍无法访问tg、tmdb的问题

---

app/plugins/autosignin/sites/hd4fans.py

源代码中判断逻辑为
`_repeat_text = '<span id="checkedin">[签到成功]</span>' `
查看兽站网页源码应该为
`_repeat_text = '<span id="checkedin" style="display: none;">[签到成功]</span>' `
个人感觉 直接判断'签到成功'更为妥当
发现代码中已经定义 变量为
`_success_text='签到成功'`
不知道原开发者为何这样写 所以说明一下

fix 兽站签到bug

---

README.md
app/chain/download.py
app/core/config.py

DOWNLOAD_PATH: str = "/downloads"
DOWNLOAD_MOVIE_PATH: str = DOWNLOAD_PATH
DOWNLOAD_TV_PATH: str = DOWNLOAD_PATH
不填默认用DOWNLOAD_PATH

feat 电影电视剧下载一级目录

---

app/plugins/torrenttransfer/__init__.py

torrent_fastresume和torrent文件字段内容不一样
Torrent.from_file(fastresume_file)返回None

fix 解析torrent_fastresume

---

app/chain/subscribe.py

如果我理解无误的话，对于现有代码，假设订阅一共有十集，用户自定义的起始集数为四，用户刚好下载到第三集，那么：
1. 第一次检测到第四集更新（正常）
走正常逻辑，batch_download 下载第四集成功后，lefts  更新为 [5,10]，lack_episodes 更新为 6。
2. 未检测到第五集更新（异常）
由于设置了起始集数， no_exists 仍然为 [4,10]，第四集走到了 __check_subscribe_note 里被跳过，导致 left = no_exists， lack_episodes 更新回 7。
3. 第一次检测到第五集更新（异常）
初始 no_exists 为 [4,10]，第四集走到 __check_subscribe_note 里被跳过，第五集正常下载，lefts 变成 [4] & [6, 10]，lack_episodes 仍然更新为 6。
后续同理，将导致 lack_episodes 永远停留在 total - start + 1（有更新时会短暂变成 total - start）。
想到的解决办法有两种：
1. __check_subscribe_note 条件成立时手动做 `no_exists -= torrent_meta.episode_list` （循环里做代价有点大）
2. 缩小初始左边界，由 用户自定义的起始集数 修改为 max(用户自定义的起始集数，媒体库内实际的起始集数）
该 PR 使用了方法 2。
close #402

fix: 修复自定义开始集导致的订阅集数不刷新问题

---

app/modules/emby/emby.py

刮削完通知emby时获取的媒体库id错误，导致我的媒体库每次新增电影都不会刷新

修复通知emby时libraryId错误bug

---

app/plugins/doubanrank/__init__.py

每次运行完保存配置list转str类型，字符串是,分隔 ，下次再运行时用\n分割 得不到正确的rss地址

fix 豆瓣榜单插件

---

app/chain/torrents.py

当 rss 和 search interval 设置为min的时候，ttl最后一秒没过期，导致 min_interval*2 生效，受影响的有brush，和rss订阅。

fix torrent_cache ttl

---

app/utils/singleton.py

方便插件创建多个下载器对象，用来的单例模式不管构造函数的参数是否不同，都是同一个对象，涉及多个下载器的插件编写不了。
改动后

fix singleton.py

---

app/chain/mediaserver.py
app/db/mediaserver_oper.py
app/db/models/mediaserver.py

`MediaServerItem` 以下情况出现残留：
1. 配置多类型 `MEDIASERVER`；
2. 之前配置了多个类型 `MEDIASERVER`，后减少一种类型
当前修改直接清空 MediaServerItem 表

fix: 清空 MediaServerItem 表

---

app/chain/transfer.py

由于 Telegram 发送消息的实现将 title 包在了一个加粗的 tag 中 https://github.com/jxxghp/MoviePilot/blob/7d7539df4cae2ad47ec14852b6beca5875d7017a/app/modules/telegram/telegram.py#L83C26-L83C26
导致其中的代码块异常
PR 将消息拆分成了 title 和 text，代码块放在了 text 中，显示就正常了
同时检查了，其他推送渠道都是将 title 和 text 拼接，应该是没有影响的

修复无法入库消息发送到 Telegram 时格式异常

---

app/modules/themoviedb/scraper.py

迷宫饭 - S01E01 - 1080p - WEB-DL - X264 - DDP 5.1 - NF - ADWeb.mkv
刮削集图片出错。
file_path.with_name(file_path.stem + "-thumb") 返回结果是
`迷宫饭 - S01E01 - 1080p - WEB-DL - X264 - DDP 5.1 - NF - ADWeb-thumb`
file_path.with_name(file_path.stem + "-thumb").with_suffix(Path(episode_image).suffix)时，会把`.1 - NF - ADWeb-thumb`当做后缀替换成`.jpg`
得到错误的集缩略图`迷宫饭 - S01E01 - 1080p - WEB-DL - X264 - DDP 5.jpg`
预先给他一个后缀名就OK，这个预先的后缀名会被替换成正确的后缀名
`.with_suffix(suffix) 添加后缀，会把最后一个.之后的内容作为后缀名，如果已经有后缀则替换`

fix 集如果带有.会刮削错误

---

update

之前通过`CURL_HEADERS="--header 'Authorization: Bearer ${GITHUB_TOKEN}'"`的方式设置认证请求头，命令实际执行的时候，会报错，导致`GITHUB_TOKEN`参数应用失败，具体错误如下所示：
```
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  5770  100  5770    0     0   8877      0 --:--:-- --:--:-- --:--:--  8945
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (6) Could not resolve host: Bearer
curl: (3) URL using bad/illegal format or missing URL
```

fix:修复bearer auth请求头设置错误,导致github_token参数应用失败

---

app/modules/qbittorrent/__init__.py

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-list 
pausedDL	Torrent is paused and has NOT finished downloading
官网看到的值是pausedDL 而不是 paused

fix: 更新qbittorrent下载判断值

---

app/chain/search.py

如果限制的大小的最小值是 0或者不填时会出问题
```
a = 0
if a:
print("ahh")
else:
print("kljlkj")
```
会打印 kljlkj，在项目中就会当前没有 begin_size 处理，就会导致大小限制失效

Fixed #1416

---

app/api/endpoints/transfer.py

在历史记录页面对移动成功的文件进行重新整理时，原代码会直接删除已经成功转移的文件，造成转移失败 & 文件丢失
对于成功的转移，则使用目标位置作为转移来源

fix: 历史记录中重新整理成功记录时的问题

---

app/chain/torrents.py
app/helper/rss.py
app/modules/indexer/spider.py

老大, 内置的100条和20到30秒的请求超时, 无法满足扩展部分自定义站点。
导致请求经常超时, 搜索结果几百条只提取前100条, 订阅不到部分旧资源。
修改后自定义站点增加两个参数可自行设定站点结果数量和请求超时
{
"id": "xxxxxxxxx",
"name": "xxxxxxxxx",
"domain": f"http://{domain}/",
"encoding": "UTF-8",
"public": True,
"search": {
"paths": [ ................

让自定义站点可自行设置: 搜索结果条数/请求超时

---

update

mv 命令会将源文件或目录移动到目标目录下，如果目标目录已经存在，那么源文件或目录会被移动到目标目录内成为其子目录。
所以当/app内的子目录被映射出去时, rm -rf命令无法删除该目录 导致更新程序会将后端程序App 与前端程序dist移动为子目录

fix 后端程序目录不正确/其他目录被映射时mv会失败

---

app/chain/subscribe.py

昨天那个暴雪时分就是 总集数变小的情况，之前只认为总集数增大才是正确最新集数。现在check已经不依赖cache了，只要总集数大于0（排除网络原因获取信息获取失败为0），就应该认为是最新的正确的总集数。

fix 总集数减小时，不能正确更新元数据

---

app/api/endpoints/login.py

此前无法通过冻结或解冻 对“辅助验证用户”账户进行操作
增加了该部分的判断

fix: Add a validation check to see if "assisted verification users" are active when logging in.

---

app/modules/filetransfer/__init__.py

没开下载器监控转移  这个测试应该没啥意义
目录监控里 设置正确就行了

fix 不开下载器监控，link测试无意义

---

app/modules/emby/emby.py
app/modules/jellyfin/jellyfin.py

jellyfin
请求RemoteImages，ProviderName自带只有"TheMovieDb"、"The Open Movie Database"：
其中经个人测试"TheMovieDb"请求几乎无效（？）；
而"The Open Movie Database"只有"Primary"类型的图片（Score排序），普遍加载很久（超时）。
所以，使用本地图片作为备选。
emby
请求RemoteImages，可能是接口问题，导致返回
`{'Images': [], 'TotalRecordCount': 0, 'Providers': []}`
需要加上Images内容检测。
也加上使用本地图片作为备选。
两者使用本地图片都需要填写各自外网播放地址。
#1520

fix 播放微信消息推送图片问题

---

app/modules/emby/emby.py
app/modules/jellyfin/jellyfin.py

jellyfin播放剧集时webhook消息的ItemId是当前集（如S01E02），接口items/{itemid}/images/{imagetype}请求剧集则是需要剧集的ItemId（剧集主页）。
所以先查询是否有父item。
emby一切正常。
---
👇

fix 播放剧集微信消息推送图片&语法问题

---

app/modules/transmission/transmission.py

修复TR限速问题，同QB相同，关联
https://github.com/jxxghp/MoviePilot-Plugins/issues/104
代码在本地可被执行，功能验证正常，请求合并主分支。

fix: TR远程控制插件限速问题 104

---

.gitignore
app/api/servcookie.py
app/chain/site.py
app/core/config.py
app/helper/cookiecloud.py
app/main.py
app/schemas/__init__.py
app/schemas/servcookie.py
app/utils/common.py
config/app.env

集成CookieCloud服务器端到MP中，无需再单独部署CookieCloud服务器或使用外部服务。
已进行了较完整的本地和局域网访问测试，可以正常工作
通过 `COOKIECLOUD_ENABLE_LOCAL` 控制本地服务开关，**本版本默认关闭**
目前启用后，可通过`http://localhost:3001/cookiecloud/`访问
后续需要更新：
-  前端服务
- 支持页面上配置是否启用本地CookieCloud服务器
- 更改反向代理配置，使`http://localhost:3000/cookiecloud/` 也能访问
-  插件兼容升级，自定义站点
后续我这边会提交相应的PR

集成CookieCloud服务器端

---

app/modules/douban/scraper.py
app/modules/themoviedb/scraper.py

处理媒体库的nfo文件，这里不需要”添加时间“
合理的设置应该是媒体文件的创建日期：
目前代码的这种写法会导致在覆写所有元数据后，各种入库时间发生混乱，进而影响媒体库首屏媒体展示
这里最合理的修改是现在这里直接删除 ”添加时间 “
若认为此方案修改有风险，可以写个插件专门删除或修正nfo文件的”添加时间“节点

NFO文件 无需 "添加时间"

---

app/modules/bangumi/bangumi.py

通过v0/subjects/%s/persons获取到的并非演员信息，而是制作组信息，例如音效、企划、动效等人员信息。这些是用户不怎么关注的。
before:
after:

fix 修改bangumi获取演职人员信息的接口

---

app/chain/subscribe.py

当删除站点后，这个站点相关的订阅依旧会使用这个站点ID，导致站点列表中出现数字。
这个bug还可能产生另一个副作用，删除后再新增一个其它站点，由于新站点会复用之前删除的ID，这个ID相关的订阅就会在这个新站点上继续订阅，这可能是用户预期外的行为。
目前我的修改方案是当删除站点时，从相关的订阅中移除这个站点，确保了不会残留无效ID在站点列表中。
对于已经残留了ID的旧数据，暂时没做处理。

fix 删除站点会导致其订阅的站点列表出现数字ID

---

app/chain/site.py

当站点没有单独设置UA的情况下，应该以系统设置中的UA为准。
解决了馒头、学校等站点的连通性测试报错的问题。

fix: 站点User-Agent没有设置的情况下以系统设置的UA进行访问

---

app/utils/singleton.py

docker启动时发现日志重复打印，推断是PluginManager()的时候PluginManager的__init__方法执行了多次。
可能install_online_plugin方法如果插件仓库配置的很多，导致init需要时间，没有第一时间生成实例。
但是单例模式没加锁，多次PluginManager()的情况下实际上导致init了多次。
经测试，init方法如果耗时的话，多线程场景下确实会多次init，加锁后只会执行一次。

fix 单例加锁，防止init方法时间过长导致多次init

---

app/core/plugin.py
app/main.py

没找到 啥原因，实测release没问题，dev就是加载了3遍。
start_module的时候调用一次安装在线插件和加载插件
不放PluginManager的init了 。
已放线上docker容器测试。

fix 插件多次加载

---

app/api/endpoints/system.py

修改后端api接口路由格式，proxy放前面确保正确解析，imgurl不再对斜杠编码，防止被反向代理拦截。

fix 编码斜杠禁用的反代无法加载图片

---

app/api/endpoints/system.py

路径参数中有`http://`会被优化为`http:/`，把url改为查询参数。

fix 反向代理图片显示问题，url改为查询参数避免双斜杠的优化

---

app/core/plugin.py

优化安装插件或者卸载重装后，插件没有按加载顺序排序，重启后又恢复正常的问题

fix plugin_order

---

app/core/metainfo.py

从标题获取 metainfo 之后需要把 tmdbid 转成 int 类型，否则会导致后面 tmdbid 匹配的时候对不上

从标题获取 metainfo 之后需要把 tmdbid 转成 int 类型

---

.gitignore
app/helper/torrent.py

TMDB: [真爱历险](https://www.themoviedb.org/movie/1285868) (2024)
在HDFANS搜索上述资源时，发现副标题种存在资源名称但无法正确匹配，检查后发现副标题分隔符中包含`【】`字符。
副标题: `真爱历险【4K EDR高码率+杜比音效】【导演：雪涛 | 主演：刘亭驿 | 董阿娇 | 梁作诗 | 文雯】QHstudIo小组作品`
副标题匹配代码原效果如下
```python 
>>> {StringUtils.clear_upper(t) for t in re.split(r'[\s/|]+', "真爱历险【4K EDR高码率+杜比音效】【导演：雪涛 | 主演：刘亭驿 | 董阿娇 | 梁作诗 | 文雯】QHstudIo小组作品") if t}
{'真爱历险4K', '主演刘亭驿', '梁作诗', '董阿娇', '文雯QHSTUDIO小组作品', 'EDR高码率杜比音效导演雪涛'}
```
其中真爱历险4K被匹配到了一个字符串中，无法正确完整匹配。
修复后效果如下：
```python 
>>> {StringUtils.clear_upper(t) for t in re.split(r'[\s/【】|]+', "真爱历险【4K EDR高码率+杜比音效】【导演：雪涛 | 主演：刘亭驿 | 董阿娇 | 梁作诗 | 文雯】QHstudIo小组作品") if t}
{'真爱历险', '4K', '主演刘亭驿', '导演雪涛', '梁作诗', 'EDR高码率杜比音效', '文雯', 'QHSTUDIO小组作品', '董阿娇'}
```

修复副标题包含【】的情况下无法匹配标题的问题

---

app/modules/jellyfin/jellyfin.py

jellyfin webhook插件返回的数据不固定，有时不含“PlaybackPositionTicks”与“RunTimeTicks”

fix: jellyfin webhook百分比数据有时为None引发报错

---

app/modules/plex/plex.py

Plex部分刷新需要传入文件的`父目录路径`才能刷新，而不是传入`文件路径`
**fix前**的`mediaserverrefresh.log`:
```bash
【INFO】2024-05-28 00:56:33,879 - mediaserverrefresh - 延迟 0 秒后刷新媒体库... 
【INFO】2024-05-28 00:56:34,568 - plex.py - 刷新媒体库：3 - /home/Library/电视剧/国产剧/武庚纪之天启 (2017)/Season 1/武庚纪之天启 - S01E04.mp4
```
**fix前**的`Plex日志`:
```bash
May 28, 2024 00:56:34.573 [139442805287736] DEBUG - Activity: registered new activity 7bb6eb50-c873-4c28-8c4e-8ccba2b1e0de - "Scanning"
May 28, 2024 00:56:34.573 [139442805287736] DEBUG - Scanning section 3
May 28, 2024 00:56:34.573 [139442805287736] DEBUG - Activity: updated activity 7bb6eb50-c873-4c28-8c4e-8ccba2b1e0de - completed 0.0% - Scanning 国产剧
May 28, 2024 00:56:35.508 [139442805287736] DEBUG - Scanning 国产剧 using zh-CN(Plex TV Series) with 0 current media items and 1 section locations …
```

fix: Plex刷新媒体库无用

---

app/helper/module.py

因PlexAutoSkip插件递归二级模块reload时出现未知异常，当前仅reload一级子模块

fix 插件重载时，支持reload一级子模块

---

app/modules/themoviedb/tmdbapi.py
app/modules/themoviedb/tmdbv3api/objs/discover.py

发现电影discover_movies报错unhashable type: 'dict'
由于 cachetools 的 cached 装饰器无法处理字典类型的参数，因为字典是可变的，不可哈希。
在使用 cached 装饰器时，需要将字典转换为可哈希的类型（例如元组）。

fix unhashable type: 'dict'

---

app/chain/transfer.py
app/utils/system.py

- 硬链接逻辑调整为目标文件增加.mp后缀，hardlink后再重命名
- 原有判断硬链接逻辑保留，调整为通过samefile判断，兼容同盘不同虚拟目录能够硬链接成功的系统

fix #667 优化历史兼容极空间硬链接逻辑

---

app/core/config.py

Apple 严格校验 mailto 必须为 `mailto:example@example.com`

fix mailto移除空格和尖括号

---

app/utils/string.py

str.isalpha()方法对于中文也是返回True的，这个导致搜索的时候很多资源没有匹配上。
>>> "汉字".isalpha()
True
>>> "汉字".encode().isalpha()
False
>>>
>>> "汉字123".encode().isalpha()
False
>>> "123".encode().isalpha()
False
>>> "abc".encode().isalpha()
True
>>> "abc1".encode().isalpha()
False

is_english_word 方法 更新

---

app/chain/site.py
app/core/config.py

1.禁用的站点基本是关站的没必要再检查ck同步ck
2.浏览器cookiecloud配置域名黑名单可以，但是设备多，浏览器多，配置多，再重装个系统啥的，还得重新配置，要不mp加个黑明单过滤掉吧

fix cookiecloud同步只同步启用的站点 && 同步域名黑名单

---

app/modules/emby/emby.py
app/modules/jellyfin/jellyfin.py
app/modules/plex/plex.py
app/utils/http.py

- RequestUtils 重构，增加request，put，put_res 方法，统一 GET POST PUT 请求入口，同时支持kwargs
- RequestUtils 请求失败时，记录debug日志
- RequestUtils 增加standardize_base_url，adapt_request_url方法，用于适配host和endpoint的处理，支持emby，jellyfin，plex调用
- Plex 增加公共请求方法
- 已通过本地测试，**调整影响较大，请Review**

RequestUtils 重构

---

app/core/plugin.py
app/scheduler.py

如果插件具有认证级别且当前认证级别不足，则不进行实例化，避免无意义的实例以及插件后台任务，同时避免部分插件因为认证级别不足时实例化出现未知问题。

fix plugin auth_level

---

app/modules/douban/__init__.py

- 优化豆瓣search_access_rate_limit时的提示，避免更具体的日志被前置判断吃掉。

fix douban rate_limit tips

---

app/core/config.py
app/helper/doh.py
config/app.env

应该在配置站点设置的时候增加一个设置，将开启 DOH 域名解析的站点的域名加入列表，但由于这部分代码不开源，因此只是简单实现了自定义域名的部分

feat:将使用 DOH 域名解析的域名添加至 app.core.config.settings #2502

---

app/modules/telegram/telegram.py

在`app/modules/telegram/telegram.py`的函数`__send_request`中
如果字符串`caption`中包含不成对的:下划线'_', 星号'*', 反引号'`'
发送消息出去就会报错: `A request to the Telegram API was unsuccessful. Error code: 400. Description: Bad Request: can't parse entities: Can't find end of the entity starting at byte offset 0, 3 秒后重试 ...`
比如: 当`caption`是
```
*开始播放电影 哆啦A梦：2112年哆啦A梦的诞生 (1995)*\n用户：brett_dean\n设备：iPhone  \nIP地址：xxx.xxx.xxx.xxx X国[XX] XX省 XX市 XX区\n剧情：《2112年哆啦A梦的诞生》（日语：2112年 ドラえもん誕生）是1995年3月4日公映的哆啦A梦附篇电影，由米谷良知导演，原作者藤子·F·不二雄，与《大雄的创世日记》同时上映。片长30分钟，主要叙述...\n时间：2024-xx-xx xx:xx:xx\n[查看详情](https://xxx.xxx.com/web/index.html#!/server/xxxxx/details?key=xxxx)
```
的时候，就会因为 `用户：brett_dean` 中含有下划线`_`而报错
所以发消息前要先转义一下，转义后即可正常发送:
---
>api说明: https://core.telegram.org/bots/api#markdown-style
>
>```bash
>Please note:
>To escape characters …
```

Fixed parsing of Telegram entities

---

app/modules/plex/plex.py
app/modules/telegram/telegram.py
app/utils/http.py

- 完善Plex中的`get_remote_image_by_id`逻辑，如果配置了外网播放地址以及Token，则默认从Plex媒体服务器获取图片，否则返回有外网地址的图片资源
- 优化telegram发送`image`消息逻辑，临时文件名通过UUID随机生成，避免Url携带参数导致文件写入失败
- RequestUtils增加`combine_url`方法
- 后续可以考虑增加`UrlUtils`再进一步重构

fix jxxghp/MoviePilot-Plugins#38

---

app/db/models/transferhistory.py

目前 history/transfer 接口仅模糊匹配了`src`（源目录）、`dest`（目标目录），应该增加对`title`（标题）的查询

feat: 历史记录查询增加对`title`字段的搜索

---

.gitignore
app/modules/wechat/wechat.py

[微信文档](https://developer.work.weixin.qq.com/document/path/90236)中有：
>| 参数    | 是否必须 | 说明                                                         |
>| ------- | -------- | ------------------------------------------------------------ |
>| content | 是       | 消息内容，最长不超过2048个字节，超过将截断**（支持id转译）** |                                                        |
>
故使用`查询订阅`或`正在下载`时，有可能因为消息过长而被截断，具体表现就是`只发送前2048字节，多余的直接丢弃`:

优化微信文本消息发送：支持长文本分块发送

---

app/main.py

- 针对站点认证及索引资源包相关的 `import`，启动时进行容错并打印友好提示
-  `sys.exit` 或者 `kill` 似乎无法直接影响到docker的异常重启，后续可考虑在 `Dockerfile` 中加入健康检查

fix SitesHelper import tips

---

app/core/config.py
app/helper/plugin.py
update

意图解决不使用全局代理或全局代理后，也无法解决插件依赖下载的问题。
针对于存在依赖下载超时的情况的时候，可以使用各大镜像源，也可自己使用CloudFlare Workers自搭建镜像源，推荐使用CF自搭建，国内源有更新延迟的问题。
附CF版自搭建PYPI镜像站项目：
https://github.com/hamidrezafarzin/Cloudflare-PyPI-Mirror-Worker

增加``PIP_PROXY``变量，支持用镜像站下载与更新依赖

---

app/chain/site.py
app/helper/rss.py
app/modules/indexer/parser/discuz.py
app/modules/indexer/parser/file_list.py
app/modules/indexer/parser/gazelle.py
app/modules/indexer/parser/ipt_project.py
app/modules/indexer/parser/nexus_hhanclub.py
app/modules/indexer/parser/nexus_php.py
app/modules/indexer/parser/small_horse.py
app/modules/indexer/parser/torrent_leech.py
app/modules/indexer/parser/unit3d.py
app/utils/site.py
app/utils/string.py

- 增加 `StringUtils.is_valid_html_element` 检查 HTML 元素，从而避免 FutureWarning
- 参考资料 https://lxml.de/api/xml.etree.ElementTree-pysrc.html

fix(lxml): Adjust HTML element checks to prevent FutureWarning

---

app/api/endpoints/plugin.py
app/api/endpoints/system.py
app/core/config.py
app/core/plugin.py
app/log.py
app/utils/system.py
config/app.env

- `API_TOKEN` 初始值调整为空，并支持 `API_TOKEN` 校验与随机生成
- 插件 API 注册时，除明确标识 `allow_anonymous`，否则统一添加 `API_TOKEN` 校验，确保安全访问
- 部分重构，完善 `SystemUtils.get_config_path` 及 `SystemUtils.get_env_path`

feat(auth): add API_TOKEN validation and auto-generation

---

app/chain/search.py
app/core/context.py
app/modules/themoviedb/tmdbapi.py

蜜柑、动漫花园部分字幕组、发布组采用台湾译名（baha等web-dl搬运），search匹配更多译名便于识别

feat:查询种子时匹配香港、台湾译名

---

app/api/endpoints/plugin.py

- 校验 `API_TOKEN` 修改为使用 `verify_apikey`，从而兼容大多数的 v1 插件

fix(plugin): use verify_apikey for backward compatibility

---

app/modules/filemanager/storages/rclone.py
app/modules/filemanager/storages/u115.py

- 解决前端调用时，没有认证参数或者失效时，后端返回的None，会引发pydantic的报错，从而导致的前端无法获取结果，卡在刷新页面

fix: cloud disk bug

---

app/utils/system.py

CPython 的 `Path.glob`/`Path.rglob` 有意去除了软链跟踪，不会往软链的目录下匹配，导致漏掉文件。
可以使用 `glob.glob` 并启用 `recursive=True` 参数。详见 CPython 相关 issue 讨论串 [^1] 以及 `glob.glob` 文档 [^2]
[^1]: https://github.com/python/cpython/issues/77609
[^2]: https://docs.python.org/3/library/glob.html

fix: `SystemUtils.list_files` 和 `SystemUtils.exits_files` 漏掉软链目录下的文件

---

.gitignore
app/helper/downloader.py
app/helper/mediaserver.py
app/helper/notification.py
app/helper/servicebase.py
app/helper/serviceconfig.py
app/modules/__init__.py
app/modules/emby/__init__.py
app/modules/jellyfin/__init__.py
app/modules/plex/__init__.py
app/schemas/system.py

- 引入 `ServiceBaseHelper` 以及 `ServiceInfo` ，用于实现获取服务配置和实例的通用逻辑
- 整合各个模块 `Helper` 之间的依赖关系，确保它们能够通过 `ServiceBaseHelper` 获取对应的服务信息

feat(module): add ServiceBaseHelper for service and instance

---

app/modules/jellyfin/__init__.py
app/modules/plex/__init__.py

- 修复了 Plex 和 Jellyfin 媒体库统计错误的问题

fix(mediaserver): resolve media_statistic

---

app/api/endpoints/system.py
app/chain/subscribe.py
app/core/config.py
app/schemas/types.py

- `set_key` 统一调整为使用 `update_setting`，并支持校验及自动修正
- `set_setting` 中涉及 `SystemConfig` 表的配置项，调整为仅支持修改已在 `SystemConfigKey` 中定义的配置
- `API_TOKEN` 调整为长度不足 16 字符时，自动生成新的符合安全要求的 `API_TOKEN`

feat(config): centralize set_key usage through update_setting method

---

app/api/endpoints/system.py

立即调用一次定时服务。
- path: `/api/v1/system/runscheduler2`
- params:
* `token`: 校验 API_TOKEN
* `jobid`: 定时服务名称
本接口同 `app.api.endpoints.dashboard.schedule2` (`/api/v1/dashboard/schedule2`) 对应，同样通过 API_TOKEN 校验。
可从 `/api/v1/dashboard/schedule2` 列出所有已开启定时服务，再通过本接口调用一次所需服务。例如，外部下载程序完成下载后需要立即整理目录，可设置钩子
```
curl 'http://moviepilot:3000/api/v1/system/runscheduler2?token=moviepilot&jobid=DirMonitor'
```

feat: 新增 API_TOKEN 接口 `runscheduler2`，立即调用一次定时服务

---

app/api/endpoints/douban.py
app/api/endpoints/login.py
app/api/endpoints/system.py
app/core/config.py
app/core/security.py
app/schemas/token.py

- 在部分匿名接口中加入 `resource_token` 认证，减少 SSRF 攻击风险
- `resource_token` 通过 **HttpOnly Cookie** 存储，避免令牌暴露在查询参数中，提升安全性
- 使用 **HttpOnly** 和 **SameSite=Strict** 的 Cookie 设置，降低 CSRF 攻击风险
- 支持 HTTPS 环境下严格传输 Cookie，确保安全性
- 通过会话级别 Cookie 和短时有效的 `resource_token`，浏览器关闭时自动失效
- 实现自动刷新机制，无需依赖 Session，确保 `resource_token` 在会话期间保持有效

feat(security): add resource token authentication using HttpOnly Cookie

---

update

- 原本比较不支持的带 `-` 的特殊后缀版本，现已支持，且内置4种英文格式的后缀（可修改）。
-  特殊后缀优先级：alpha < beta < rc < stable < 数字大小
- 版本优先级：v1.9.17-alpha < v1.9.17 < v1.9.17-2 < v2.0.0-alpha < v2.0.0 < v2.0.0-2

feat(update):  解决v2版本启动时，被v1反向更新覆盖的问题

---

requirements.in

- 更新 `qbittorrent-api` 至 `2024.9.67` 以支持 qBittorrent 5.0

chore(deps): upgrade qbittorrent-api to support qbittorrent 5.0

---

app/modules/qbittorrent/qbittorrent.py

`status` 在 qBittorrent 的历史版本中应该也不支持数组传递，最新的 SDK 中因接口调整后直接抛出异常，这里为了过滤逻辑的准确性，暂不对传入 `list` 进行兼容性处理

feat(downloader): add compatibility support for qBittorrent 5.0

---

app/api/endpoints/login.py
app/chain/user.py
app/core/config.py
app/db/models/user.py
app/db/user_oper.py
app/modules/emby/__init__.py
app/modules/jellyfin/__init__.py
app/schemas/event.py
app/schemas/types.py
config/app.env

- 使用 `UserChain` 作为统一入口，支持 `password` 和 `authorization_code`（待新增认证接口）等多种认证策略。通过事件机制扩展认证流程，允许扩展集成 OAuth2 和 OpenID Connect 等协议
- 本地认证失败时，根据配置判断是否启用辅助认证。若启用，系统通过预置模块进行认证，支持多重身份验证源
- 根据 `grant_type` 区分认证策略，并触发外部认证事件
- 暂不支持非 `password` 认证的 MFA 校验
- `password` 策略可自动创建用户，其他策略需返回已存在的用户，否则认证失败
- 本地和预置模块认证失败时，触发外部认证事件，允许通过外部模块进行扩展认证

feat(auth): enhance auxiliary authentication

---

update

- 修复了因主版本号的 v 前缀未去除而导致无法判断的问题。
- 增加了对非法版本号的识别。
- 将 `cat` 替换为 `grep` 并进行优化，即使 `version.py` 增加更多值，也能正常使用。
- 修复了 `cat` 获取的值中存在回车符、换行符，从而导致参数无法被版本判断正常识别使用的问题。
- 增加了自动排除 `version.py` 文件中变量行末尾注释的功能，并自动去除首尾多余空格，以确保始终能正确获取到需要的值。

fix(update)

---

app/api/endpoints/message.py
app/modules/__init__.py
app/modules/qbittorrent/__init__.py
app/modules/slack/__init__.py
app/modules/synologychat/__init__.py
app/modules/telegram/__init__.py
app/modules/transmission/__init__.py
app/modules/vocechat/__init__.py
app/modules/wechat/__init__.py

- 通过统一获取配置的逻辑，简化了配置管理以及降低用户配置难度
- `get_config` 和 `get_instance` 调整为支持可选服务名称，如果未提供服务名称，则系统将返回默认值
- 默认配置的获取逻辑调整如下：
- 如果存在已设置为默认的配置，则返回该默认配置
- 如果没有默认配置，则返回第一个配置的名称
- 如果没有任何配置，返回 `None`

refactor(module): unify config retrieval logic

---

app/modules/wechat/__init__.py

- 添加企业微信的菜单校验，没有配置消息解密参数时，则取消初始化菜单

feat(command): add validation for menu configuration

---

app/monitor.py

monitor.py - 目录监控发生错误：expected string or bytes-like object, got 'PosixPath' - Traceback (most recent call last):
File "/app/app/monitor.py", line 301, in __handle_file
if keyword and re.search(r"%s" % keyword, event_path, re.IGNORECASE):
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/re/__init__.py", line 176, in search
return _compile(pattern, flags).search(string)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'PosixPath'

fix dirmonitor exclude_words

---

app/chain/transfer.py

fix: 
#2865 
~~#2926~~ 目录包含被排除项,不会递归查找文件, 并不会修复这个问题
- 修复因首个子目录中无目标文件而不处理整个文件夹的问题
- 同时增加了整理 `音轨文件`
***
修改说明: 
- 1f6fa22 修复了多个类型为`目录` 时, `file_items` 被覆盖的问题
- d108b0d 仅处理了缩进, 无其他改动
-  0ee21b3
- - 汇总处理所有目录, 这样能提供更准确的`总文件数`,同时减少`for`嵌套
- - 移出 `for trans_item in trans_items` 循环体中的 `变量声明` 
- - 修复手动整理选中多个文件或文件夹时,  选中的`文件夹`中的`第一个子目录`中`不存在符合条件`的文件就不处理整个`文件夹`的问题

修复 `Blu-ray` 等存在子目录,但第一个子目录内不存在目标文件而跳过处理整个目录的问题

---

app/db/models/siteuserdata.py

实际上ck没过期，mp上可测试通过、查看种子、查看数据，但是latest最新数据都是0

fix 获取站点最新数据的时候排除掉错误的数据

---

app/chain/storage.py

fix: #2941 
>`delete_media_file` 返回值现修改为:
>- `目录存在其他媒体文件`时返回`文件删除状态`
>- `目录不存在其他媒体文件`时返回`目录删除状态`

fix: 删除历史记录报错

---

app/chain/subscribe.py

fix: #2945
- 修复 `新增订阅搜索` 阶段 `包含/排除规则` 不生效的问题

fix: `包含/排除规则` 在新增订阅搜索无效的问题

---

app/helper/directory.py

fix: #2963
- `if src_path and download_path != src_path`：已排除未设置下载目录的情况
- `if dest_path and library_path != dest_path`：已排除未设置媒体库目录的情况
因此，`if not d.download_path or not d.library_path` 条件不再需要。

fix: #2963

---

app/monitor.py

close: #2962
修复了未能将`library_path`传递给`transfer`(文件转移)模块的问题
以此修复`目录监控`模式下,文件都被错误的整理到第一顺位的`媒体库目录`

fix: 修复了`整理模式`为`目录监控`时, 目标路径不符预期的问题

---

app/utils/system.py

原 glob(str(directory / '**'), recursive=recursive, include_hidden=True) 获取子目录及文件的方式，对于特殊字符的目录会形成类似 '/tmp/test/[abc][01]/**' 的 pathname，会返回空列表。
修改为 glob('**', root_dir=directory, recursive=recursive, include_hidden=True)，显示指定root_dir，可以成功获取列表

改进 SystemUtils.list_files 遍历目录对特殊字符的兼容性（如'[]'）

---

app/helper/directory.py
app/modules/filemanager/__init__.py

- 修复了在`手动整理`时，
`目的路径`留空（自动选择）且`媒体类型`和`媒体类别`相同但路径不同的情况下，
返回首个`媒体库目录`的问题.

fix: 修复了在某些特定场景下，`手动整理`无法正确获取目标路径的问题。

---

app/core/meta/metaanime.py
app/modules/douban/__init__.py
app/modules/themoviedb/__init__.py

perfect：MetaAnime.cn_name 属性不再进行简化处理，在使用 TMDB 和豆瓣查询时再查询简体化名字
提高动漫识别准确性
- `[ANi] 學姊是男孩 - 09 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4`
- `[ANi]我家有個魚乾妹 [01][1080P][Baha][WEB-DL].mp4`
- `[HKGS]滿腦都是○○的我沒辦法談戀愛[01][1080P][WEB-DL].mkv`
- `[ANi]銀河騎士傳[01][1080P][Baha][WEB-DL].mp4`

perfec：匹配未简体化的中文标题，提高动漫识别准确性

---

app/modules/douban/douban_cache.py
app/modules/themoviedb/tmdb_cache.py

- #2567 
- #2785
假设有两部剧集：
1. `[ANi] LoveLive! SuperStar!! 第三季 - 02 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4`
2. `[ANi] Re：從零開始的異世界生活 第三季 - 03 [1080P][Baha][WEB-DL][AAC AVC][CHT].mp4`
并且均设置了自定义识别词：
```
LoveLive! SuperStar!! 第三季  => {[tmdbid=106055;type=tv;s=3]}
Re：從零開始的異世界生活 第三季 - (?=(0[1-9]|1[0-6])) => {[tmdbid=65942;type=tv;s=1]} E && E <> \[1080P\] >> EP+50
```
原本的刮削的缓存key会优先使用`meta.name`这个属性，由于剧名被自定义识别词替换，name属性均为`[1080P][Baha][WEB-DL][AAC AVC][CHT]`导致缓存冲突，匹配错误缓存

fix: 优先使用id作为cache key避免key冲突（tmdb、douban）

---

app/modules/indexer/parser/nexus_rabbit.py
app/utils/site.py

此 PR 修复了白兔俱乐部的登录状态检测和站点信息获取（调试过程中发现了[一个前端 bug](https://github.com/jxxghp/MoviePilot-Frontend/pull/233)，也已一并提出）：
> <img src="https://github.com/user-attachments/assets/04c24976-db67-4660-8ef4-74b3e1dce9d4" width=50%/>
> <img src="https://github.com/user-attachments/assets/7bac621e-16db-4c2a-8a85-db7f5aea9aeb" width=50%/>
由于该站进行了诸多改动，已经不太能复用 nexus 的站点信息获取逻辑，因此将 nexus_rabbit 修改为直接继承 SiteParserBase。
索引器部分看不到具体逻辑不太好改，目前仍为故障状态。粗看了一下感觉能继续复用 nexus 的框架，但需要调整种子各部分的选择器。

fix: 修复白兔俱乐部的站点信息获取、登录状态检测

---

app/modules/filemanager/storages/alist.py

Alist驱动在微秒末位为0时会解析错误。可以直接使用ISO 8601格式解析

fix 部分情况下Alist解析时间错误

---

app/modules/filemanager/storages/rclone.py

- 写入配置时，显式使用 UTF-8
```
ERROR:   2024-11-15 17:43:48,179 chain - 运行模块 FileManagerModule.storage_usage 出错：'utf-8' codec can't decode byte 0xc7 in position 2: invalid continuation byte
Traceback (most recent call last):
File "D:\Work\InfinityPacer\MoviePilot\app\chain\__init__.py", line 112, in run_module
result = func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "D:\Work\InfinityPacer\MoviePilot\app\modules\filemanager\__init__.py", line 319, in storage_usage
return storage_oper.usage()
^^^^^^^^^^^^^^^^^^^^
File "D:\Work\InfinityPacer\MoviePilot\app\modules\filemanager\storages\rclone.py", line 342, in usage
lines = f.readlines()
^^^^^^^^^^^^^
File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc7 in position 2: invalid continuation byte
```

fix(rclone): specify UTF-8 encoding when save config

---

entrypoint
update

fix https://github.com/jxxghp/MoviePilot/issues/2996

fix(update): clear tmp directory causes data loss

---

app/modules/filemanager/storages/local.py

在日志中发现
INFO:    media.py - 开始刮削：xxxx.xxx
INFO:    media.py - 已保存文件：xxxx.nfo/
INFO:    media.py - 已保存文件：xxxx.jpg/
INFO:    media.py - xxxx.xxx 刮削完成

fix 本地存储 upload 后将文件识别为文件夹的问题

---

app/scheduler.py

fix(auth): initialize plugin service only during retry auth

---

app/core/config.py

- 调用 `update_env_config` 时传递正确的 `original_value` 以确保日志一致性
- 移除字段已存在于 `os.environ` 中时对 `is_converted` 的无效检查

fix(config): ensure accurate handling of env config updates

---

app/chain/search.py

fix #3190
bug发生时的log
```
【INFO】2024-11-21 21:53:34,099 - search.py - 过滤规则/剧集过滤完成，剩余 2 个资源
【INFO】2024-11-21 21:53:34,100 - search.py - 开始匹配结果 标题：豺狼的日子，原标题：The Day of the Jackal，别名：['Sjakalen', 'يوم إبن آوى', '자칼의 날', 'Dzień Szakala', 'A sakál napja', 'Chacal', 'התן', 'День Шакала', '豺狼的日子', 'The Day of the Jackal', '豺狼之日', 'El Chacal', 'Денят на Чакала', 'Ziua șacalului', 'Дан Шакала', 'روز شغال', 'O Dia do Chacal']
【INFO】2024-11-21 21:53:34,227 - search.py - 豺狼的日子 通过IMDBID匹配到资源：馒头 - The Day Of The Jackal S01E06 2160p NOW WEB-DL DDP5 1 Atmos H 265-FLUX
【INFO】2024-11-21 21:53:34,361 - torrent.py - The Day Of The Jackal S01E06 2160p NOW WEB-DL DDP5 1 Atmos H 265-FLUX 不匹配特效规则 [\s.]+HDR[\s.]+|HDR10|HDR10\+
【INFO】2024-11-21 21:53:34,362 - search.py - 匹配完成，共匹配到 1 个资源
【INFO】2024-11-21 …
```

将订阅规则过滤前置，避免因imdbid匹配而跳过

---

app/chain/download.py
app/chain/transfer.py
app/helper/directory.py

resolve jxxghp/MoviePilot-Frontend#247
`目录配置` 为`假`(目前仅`目录监控`有传入)， 进行目录匹配
- 源目录匹配 使用文件路径匹配, `同盘优先`使用`文件自身`的`存储类型`
- `媒体目录`匹配 处理`手动整理`的场景, 使用用户选择的`目的路径`和`目的存储`匹配
- - 有返回值使用分类策略创建目录, 用户指定的分类优先
- - None使用用户设定的`自定义目录`, 使用`手动整理`时设置的分类创建目录
- 自动匹配 处理 `手动整理` 目的路径留空和其他的场景

resolve: jxxghp/MoviePilot-Frontend#247

---

app/chain/download.py
app/chain/transfer.py
app/helper/directory.py

`不整理`目录的`下载路径`可以被下载器获取

---

app/core/config.py
app/modules/indexer/parser/__init__.py
app/modules/indexer/spider/__init__.py
app/utils/http.py

1. 新增编码探测置信度策略
- 通过新增的配置项优化编码探测逻辑，支持性能模式和兼容模式的切换
2. 新增配置项
- `ENCODING_DETECTION_PERFORMANCE_MODE`：控制是否启用性能模式。默认情况下使用兼容模式，通过依次执行 `chardet` 分析、BOM 检测、HTML meta 标签解析及响应头解析来探测编码，适用于复杂编码场景，但可能略微降低性能。启用性能模式时，探测流程优先从响应头、BOM 检测和 HTML meta 标签获取编码信息，再通过 `chardet` 分析作为补充，以提升效率
- `ENCODING_DETECTION_MIN_CONFIDENCE`：设置编码检测的置信度阈值，用于过滤低置信度结果。默认为 0.8
3. 优化探测流程
- 在性能模式下优先从响应头、BOM 检测、HTML meta 标签中提取编码信息，提高解析性能
- 在兼容模式下优先使用 `chardet` 分析结果及其他探测方式，进一步提高编码探测准确性
- 增加 `fallback_encoding`，确保在探测失败时返回 `utf-8` 或置信度较低的推测结果
4. 更多
- 目前仅优化了 HTML 内容的编码探测流程，待后续根据用户反馈进一步调整 RSS（XML）相关的编码探测逻辑

feat(encoding): enhance encoding detection with confidence threshold

---

app/chain/transfer.py

fix: 修复批量整理时`媒体库目录`匹配不正确的问题

---

app/chain/media.py
app/modules/fanart/__init__.py

修复fanart季图片下载缺失问题
修复只刮削某季却下载了所有fanart季图片的问题

fix: 修复fanart季图片下载缺失/错误的问题

---

app/db/models/downloadhistory.py

如果下载记录存在重复的情况下应该默认获取最后一条，通常情况这是和实际情况符合。因为没有记录映射关系，这是最小改动了
相关issue：https://github.com/jxxghp/MoviePilot/issues/3307

fix: return last record when get downloadhistory by hash

---

app/modules/__init__.py
app/modules/bangumi/__init__.py
app/modules/douban/__init__.py
app/modules/emby/__init__.py
app/modules/fanart/__init__.py
app/modules/filemanager/__init__.py
app/modules/filter/__init__.py
app/modules/jellyfin/__init__.py
app/modules/plex/__init__.py
app/modules/qbittorrent/__init__.py
app/modules/slack/__init__.py
app/modules/subtitle/__init__.py
app/modules/synologychat/__init__.py
app/modules/telegram/__init__.py
app/modules/themoviedb/__init__.py
app/modules/thetvdb/__init__.py
app/modules/transmission/__init__.py
app/modules/vocechat/__init__.py
app/modules/webpush/__init__.py
app/modules/wechat/__init__.py
app/schemas/types.py

- 在 `types` 里，针对各个模块的类型进行子级分类。
- 为每个模块统一添加 `get_subtype` 方法，这样一来，能更精准快速地区分与调用子类的每个模块，又能获取 ModuleType 所规定的分类以及对应存在的子模块类型支持列表，从而有效解决当下调用时需繁琐遍历每个 module 以获取 get_name 或 _channel 的问题。
- 解决因消息渠道前端返回所保存的 type 与后端规定值不一致，而需要频繁调用 _channel 私有方法才能获取分类所可能产生的问题。

feat(modules): 增加子级 `type` 分类。

---

app/chain/download.py

- 下载事件传递 `episodes` 用于明确是否为拆包下载

feat(events): add episodes field to DownloadAdded event for unpack

---

app/core/module.py
app/modules/indexer/__init__.py
app/schemas/types.py

- 补全 `indexer` 缺少 `get_subtype` 方法。
- 增加 `get_running_subtype_module` 方法，可结合 `types` 快速获取单个运行中的 `module` 。

fix(module): 补全 `indexer` 缺少的 `get_subtype` 方法

---

app/api/endpoints/subscribe.py
app/chain/subscribe.py
app/db/models/subscribe.py

1. **订阅状态增强**：
- 新增两个订阅状态：
- `P`（Pending）：表示待定状态，信息需要进一步更新，允许搜索，但不允许完成
- `S`（Suspended）：表示暂停状态，订阅不参与任何动作，暂时停止处理
- 当前订阅状态包括：
- `N`：新建（未处理）
- `R`：已处理（订阅中）
- `P`：待定（信息待进一步更新，允许搜索，不允许完成）
- `S`：暂停（不参与任何动作，暂时停止处理）
2. **新增订阅状态更新 API**：
- 新增 `PUT /api/v1/subscribe/status` 接口，用于更新订阅的状态

feat(subscribe): add Pending and Suspended subscription states

---

app/api/endpoints/download.py
app/chain/download.py
app/chain/message.py
app/chain/subscribe.py
app/core/event.py
app/schemas/event.py
app/schemas/types.py

- 新增资源下载事件，允许插件取消下载，如页面搜索下载时，插件拦截H&R种子等场景
- `download_single` 中 `source` 除消息渠道外，新增了 `Manual` 、`Subscribe` 两种场景
- 优化了链式事件的处理逻辑，避免无意义的执行

feat(event): add ResourceDownload event for cancel download

---

app/api/endpoints/subscribe.py
app/chain/subscribe.py

- 订阅重置支持重置订阅状态为 `R`
- 下载后重新获取订阅信息，从而同步外部修改，保持状态一致
- 为电影类型的订阅增加了更新已下载记录的支持
- 确保在订阅完成时优先更新状态，避免状态丢失
- 优化了剩余集数更新逻辑，避免重复更新订阅信息
- 支持通过订阅下载信息来判断订阅是否已下载，避免因订阅状态为 `待定` 时，订阅没有及时完成导致重复下载的问题
- 新增 `check_and_handle_existing_media`，统一 `RSS` 以及 `Search` 的媒体是否已经存在判断逻辑

feat: 完善订阅下载逻辑，进一步支持多种订阅状态

---

requirements.in

- 降级 115 相关依赖，避免依赖升级导致的版本兼容问题
This reverts commit d182a7079dfd532651aef01fde14b265e933144f.

Revert "chore(deps): update dependency python-115 to v0.0.9.8.8.3"

---

app/db/models/siteuserdata.py
app/db/site_oper.py

- 避免因 `db_update` 排除 None 导致 `err_msg` 无法更新，从而导致站点数据无法正常显示的问题
``` python
@db_update
def update(self, db: Session, payload: dict):
payload = {k: v for k, v in payload.items() if v is not None}
for key, value in payload.items():
setattr(self, key, value)
if inspect(self).detached:
db.add(self)
```

fix(site): avoid err_msg cannot be updated when it's None

---

app/core/config.py
app/modules/bangumi/bangumi.py
app/modules/douban/apiv2.py

1. 将豆瓣 API 的缓存逻辑拆分为两个独立的方法：
- `__invoke_recommend`：用于处理推荐/发现类 API 的缓存逻辑
- `__invoke_search`：用于处理搜索类 API 的缓存逻辑
2. 统一 Bangumi  API 的缓存管理逻辑

refactor(cache): split douban cache into recommend and search

---

app/chain/__init__.py
app/chain/download.py
app/modules/qbittorrent/__init__.py
app/modules/transmission/__init__.py

修复因`qBittorrent` 中使用不同的`种子文件布局` 而导致`数据库`字段记录`不一致`的问题
- 在 `DownloadChain` 中根据`种子文件布局`拼接`savepath`
- 在 `QbittorrentModule` 和 `TransmissionModule` 中添加种子文件布局信息
- 修改 `download` 方法的返回值，增加种子文件布局参数

refactor(downloader): 新增支持`种子文件布局`处理

---

app/modules/indexer/spider/__init__.py

TorrentSpider在使用PyQuery解析xml时，如果xml含有“encoding=xxx”字段，会因为xml的encoding问题报错，这个问题可以通过将传给PyQuery的html_text重新进行编码解决，即html_doc = PyQuery(html_text) -> html_doc = PyQuery(html_text.encode('utf-8'))
因此给indexer添加一个encoding字段，当其为True时进行encode，同时默认为False避免对已有代码产生影响

TorrentSpider添加encoding key

---

app/api/endpoints/bangumi.py
app/api/endpoints/douban.py
app/api/endpoints/tmdb.py
app/chain/recommend.py
app/utils/common.py

- **`log_execution_time`**: 新增通用装饰器，用于记录方法执行耗时，便于性能监控与调试
- **`RecommendChain`**: 
- 整合 TMDB、豆瓣、Bangumi 等推荐相关接口，统一调用逻辑
- 新增缓存方案：
- 新增自定义缓存装饰器，避免偶发网络获取数据为空时，页面由于缓存为空长时间渲染异常问题
- 推荐内容缓存有效期默认为 **6小时**，减少频繁的外部接口请求
- 支持主动更新推荐缓存，提升前端响应速度
- 缓解不同地区 CDN 节点可能存在的限流问题
1. **定时任务**：
- 增加定时任务，定期调用 `refresh_recommend`，确保缓存内容及时更新
2. **图片资源优化**：
- 当启用全局图片时，`refresh_recommend` 将支持后台预下载推荐图片资源，进一步提升加载效率
- 考虑对全局图片资源按不同域名进行细分优化，支持更精细的管理策略

feat(recommend): add RecommendChain

---

app/modules/filemanager/__init__.py

- Update season_episode field in FileManagerModule to use meta.episode instead of meta.episodes
- This change ensures accurate season and episode information is displayed

fix(filemanager): correct season_episode metadata mapping

---

app/helper/format.py

fix: #3511 移除的 `指定集数` 处理逻辑
现有问题：后端处理了多种指定集数格式（`1,2` `1-2`），而前端提示为 `1/1,2`。为了减少代码冗余，是否应去除其中一种格式的处理？

fix(format): improve episode parsing logic

---

app/chain/storage.py

修复无法删除`整理的原盘目录`的问题
- 在 `fileitem`为`目录`时, 先移除`BDMV`和`CERTIFICATE`目录。

fix(storage): delete `Blu-ray` directory when removing movie file

---

app/chain/transfer.py
app/helper/directory.py
app/monitor.py
app/schemas/transfer.py

- 统一源目录匹配逻辑
1. 移除参数 `src_match`，对源目录匹配逻辑进行统一调整
2. 调整后的匹配逻辑：  
- 优先匹配子目录：当源目录存在，且为任一下载目录的子目录时，进行源目录匹配
- 同盘优先匹配：若源目录不属于下载目录的子目录，则允许按“同盘优先”的逻辑进行匹配
- 修复的问题：
1. 解决了手工整理、下载器监控、目录监控、历史纪录重新整理等场景中，因源目录匹配逻辑不一致而导致目标目录不一致引发的类似硬链接失败等一系列问题
2. 优化匹配逻辑的统一性，确保多种场景下行为一致，实现下载目录解耦媒体库目录
- fix #3636  
- fix #3060

feat(transfer): match source dir in subdirs or prioritize same drive

---

app/chain/__init__.py
app/chain/search.py
app/chain/subscribe.py
app/helper/torrent.py
app/modules/filter/__init__.py
app/schemas/transfer.py

- 将`季集匹配`从`优先级规则组匹配模块`移至`种子帮助类`
- - `FilterModule.__match_season_episodes()` ==> `TorrentHelper.match_season_episodes()`
- - 确保需要`订阅识别词` `偏移季集`的种子能够正确匹配
- `订阅刷新`中更新应用订阅识别词的`种子元数据`,
- 附加参数过滤空项

fix: - 修复订阅识别词在下载阶段不生效的问题

---

app/api/endpoints/subscribe.py
app/schemas/types.py

- `编辑`订阅信息后，发送订阅调整事件
- 新增 `EventType.SubscribeModified` 枚举值
- 事件数据包含`subscribe_id: int` 和更新后的订阅信息`subscribe_info: dict`

feat(event): 添加订阅调整事件

---

app/chain/mediaserver.py
app/chain/recommend.py
app/chain/tmdb.py
app/core/cache.py
app/helper/plugin.py
app/helper/subscribe.py
app/modules/bangumi/bangumi.py
app/modules/douban/apiv2.py
app/modules/fanart/__init__.py
app/modules/filemanager/storages/alist.py
app/modules/plex/plex.py
app/modules/themoviedb/tmdbapi.py
app/modules/themoviedb/tmdbv3api/objs/discover.py
app/modules/themoviedb/tmdbv3api/objs/trending.py
app/modules/themoviedb/tmdbv3api/tmdb.py
app/utils/web.py
requirements.in

**此 PR 对缓存方案进行了优化和改进，主要包括以下内容：**
- 新增 `CacheBackend` 抽象类，提供统一的缓存接口
- 实现了以下两种缓存后端：  
- `CacheToolsBackend`：基于 `cachetools` 的内存缓存，支持动态 TTL 和最大容量配置
- `RedisBackend`：基于 Redis 的分布式缓存，支持区域化存储及过期管理  
- 引入 `@cached` 装饰器，简化缓存逻辑，支持动态配置如 `ttl`、`region` 和缓存条件控制（跳过空值等）  
- 将原有直接使用 `cachetools` 的逻辑统一迁移至新的缓存后端，提升了代码的一致性和可扩展性  
- 优化 `get_plugins` 方法，支持通过 `skip_empty` 参数跳过网络异常时的空结果，提升了系统的容错能力
- 引入缓存区支持，允许按业务需求对缓存数据进行隔离管理，避免不同模块间的冲突
- 此 PR 使用 `@cached` 装饰器时，将默认跳过缓存 `None`，但其他空值不限于 None,[], {}, "", set()，默认缓存
- `RedisBackend` 尚未完全实现，待进一步完善，此外 `RedisBackend` 将不再支持 maxsize，考虑通过大内存模式来统一限制

feat(cache): add cache backend implementations and decorator support

---

app/helper/module.py

- 交由 `pkgutil.walk_packages()` 来组合包名，以防止因与已导入包同名而导致的无效包名拼接问题。

refactor(app/helper): optimize module reloading mechanism

---

app/chain/subscribe.py

- 修复了在未选择默认订阅站点时，订阅任务未按指定站点执行的问题
- 移除了临时\无效订阅站点的数据库更新逻辑，允许用户通过前端自行管理

fix(subscribe): optimize site list retrieval in get_sub_sites

---

app/core/cache.py
app/modules/themoviedb/tmdbapi.py

- 重构了 `get_cache_key`，修复 `kwargs` 参数未正确捕获导致缓存键重复的问题
- 调整 `match_web` 限流基础时长为 `5s`，更精细化进行限流管理

fix(cache): ensure consistent parameter ordering in get_cache_key

---

app/chain/transfer.py

不太确定这个BUG是哪里造成的，先在求和的地方简单加一个判断过滤
```
INFO:    filemanager - 正在整理文件：【local】/media/下载/Strm/ANIOpen/2021-1/轉生成蜘蛛又怎樣！/[ANi]轉生成蜘蛛又怎樣！[16][1080P][Baha][WEB-DL].strm 到 【local】/media/媒体库/Strm/电视剧/日番/转生成蜘蛛又怎样！ (2021)/Season 1/转生成蜘蛛 又怎样！ S01E16 -1080p -ANi -Baha.strm，操作类型：link
INFO:    filemanager - /media/下载/Strm/ANIOpen/2021-1/轉生成蜘蛛又怎樣！/ 目录下没有找到字幕文件...
INFO:    filemanager - 文件 /media/下载/Strm/ANIOpen/2021-1/轉生成蜘蛛又怎樣！/[ANi]轉生成蜘蛛又怎樣！[16][1080P][Baha][WEB-DL].strm 整理成功
INFO:    transfer.py - [ANi]轉生成蜘蛛又怎樣！[16][1080P][Baha][WEB-DL].strm 入库成功：/media/媒体库/Strm/电视剧/日番/转生成蜘蛛又怎样！ (2021)/
ERROR:   transfer.py - 整理队列处理出现错误：unsupported operand type(s) for +: 'int' and 'NoneType' - Traceback (most recent call last):
File "/app/app/chain/transfer.py", line 576, in __start_transfer
state, err_msg = …
```

fix: 使用后台转移计算任务数量时某些fileitem.size是None

---

app/chain/transfer.py

当电视剧重命名格式使用了{episode_title}参数时，订阅的剧在整理后都会缺少episode_title信息，只有手动整理（不指定tmdbid、不复用历史记录）才能正确重命名。

fix 文件整理在特定情况下会缺失剧集信息

---

app/chain/site.py

当网络不稳定时，测试馒头、朱雀等站点，会误报鉴权过期或者Cookie失效。
需要明确网络原因还是账号原因，避免产生歧义。

fix 网络异常时，站点测试误报鉴权或Cookie过期

---

app/core/cache.py
app/modules/fanart/__init__.py

- 细化 `fanart` 图片请求的缓存逻辑，网络连接异常时不再缓存失败的请求结果，针对请求返回 `404` 等情况，保持原有的缓存逻辑
- 缓存装饰器中，当 `skip_none=False` 时，新增缓存键存在性检查，提高缓存策略的精细化控制
- fix #3789

fix(cache): check cache existence when skip_none is False

---

app/core/config.py
app/modules/filemanager/__init__.py
config/app.env

根据Emby、jellyfin的文件命名规则，为字幕添加.default后缀可以设置指定字幕文件为默认字幕，播放时可以不用手动选择外挂字幕文件了
[Emby命名规范](https://emby.media/support/articles/Subtitles.html)
[jellyfin命名规范](https://jellyfin.org/docs/general/server/media/external-files/)
[Plex](https://support.plex.tv/articles/200471133-adding-local-subtitles-to-your-media/)不支持这种后缀，添加上去没有用
目前是在配置文件内添加了一个配置项，默认不启用，如果启用的话需要设置环境变量DEFAULT_SUB为'zh-cn'，'zh-tw'，'eng'其中一个
处理后字幕的后缀名会变为如下格式：
.default.chi.zh-cn
.default.zh-tw
.default.eng

添加为指定字幕添加.default后缀设置为默认字幕功能

---

app/modules/themoviedb/__init__.py
app/modules/themoviedb/tmdbapi.py

fix #3912
调整tmdb识别匹配逻辑。当未提供mtype时，原来的做法会将tmdbid先当作tv去匹配tmdb_info，匹配不到才会尝试movie。修改后movie和tv都去匹配，如果同一个tmdbid在movie和tv都有结果返回则放弃用tmdbid，进入meta的判断逻辑。

fix: mtype为空且tmdbid在movie和tv中都存在时的识别错误问题

---

app/log.py

之前docker容器日志，重启完mp后，一旦插件开始工作打印log，容器日志就会重复打印 ，如下所示
INFO: subscribe.py - 故都春晓图 (2024) 未下载完整，继续订阅 ...
INFO:moviepilot:subscribe.py - 故都春晓图 (2024) 未下载完整，继续订阅 ...

fix docker container log duplicate printing

---

app/helper/rss.py

修改原因：管理员在mp添加多个豆瓣id时，不同的豆瓣用户订阅内容，发送通知时统一为“豆瓣想看”,无法区分 修改后：增加豆瓣昵称获取，便于推送订阅通知消息时，区分豆瓣用户名称

20250314 修改rss.py

---

app/chain/site.py
app/modules/indexer/spider/mtorrent.py

1. 当没有请求体的时候，不要指定Content-Type: application/json，否则馒头会因为判断Content-Length为0而报请求参数错误
2. 馒头测试逻辑移除Authorization的使用，会触发馒头的风控警告

修复馒头请求参数错误的问题

---

app/api/endpoints/system.py
app/core/meta/releasegroup.py

词表已清空但是前端传递了存在空字符串的空list:
存储的时候会原样存储:
最终在制作组匹配的时候这里的判断会为True:
最终导致制作组前面会多一个@符号:

fix: 修复前端传递了[""]这样的空list导致判空时逻辑异常的问题

---

app/utils/string.py

#4092 解决类似这样的问题，transmission因为使用了 `urlparse` 所以不会有qbittorrent的问题

perf: 优化qb下载器端口获取逻辑

---

app/core/config.py

修复 开启全局图片缓存后无法显示来自Bing的壁纸

---

app/modules/themoviedb/__init__.py

由于tmdb会返回还没有出来的季信息，而季信息的air_date又是null，导致整理的时候代码报错，进行容错判断

Update __init__.py 添加空值检查

---

app/chain/download.py
app/chain/subscribe.py
app/chain/transfer.py
app/helper/message.py

fix: #4228
- `添加订阅` 传入 `MetaBase`
- 上下文增加 `username` 字段
- 原始对象引用 `默认开启`

修复部分字段缺失的问题

---

app/chain/message.py

修复特殊微信id无法处理消息的问题 #4246

---

app/scheduler.py

#4219 避免stop()中_scheduler.shutdown()处于阻塞状态导致的死锁

fix: blocking issue

---

app/helper/plugin.py

安装插件依赖时，使用sys.executable，确保各种环境下都能使用正确的pip

Use sys.executable -m pip for env-safe package installation

---

app/core/meta/metavideo.py
app/utils/tokens.py

修复 Commit `23ef8ad` 中 `__init_video_encode` 的错误捕获组使用，现在 `x26[45]` 会正确小写
新增了 `HDR10+` 和 `HDR10Plus` 识别
移除了 `tokens.py` 中对 `+` 号的分割，以此正确识别 `AVS+ HDR10+ DD+`

fix(meta): 修复部分格式识别问题

---

app/modules/themoviedb/tmdbapi.py
database/versions/89d24811e894_2_1_4.py

- 移除 `season_group_details` 中的冗余集号处理
- 将下载模板中的 `title` 更改为 `torrent_title`

fix(themoviedb): 直接在 API 层次处理剧集组集号

---

app/chain/subscribe.py

Fixed #4306 
对于缓存中的种子，在开始订阅之前预识别， 并添加识别标记。 保证不会对无法识别到信息的种子多次识别

修复重复识别缓存种子的bug
